import { useLoading } from '@/contexts/loading-context';
import { loadMonthStartDay, monthStartEvent } from '@/hooks/use-month-start';
import { loadAllCategories } from '@/utils/categories';
import { getAllExpenses, type ExpenseRecord } from '@/utils/expenses';
import { getAllIncomes, type IncomeRecord } from '@/utils/incomes';
import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';

export interface DayDataRecord {
  [date: string]: any;
}

interface AppDataContextType {
  calendarData: DayDataRecord;
  monthStartDay: number;
  refresh: () => Promise<void>;
  isReady: boolean;
  dataVersion: number;
}

const AppDataContext = createContext<AppDataContextType | undefined>(undefined);

export const useAppData = (): AppDataContextType => {
  const ctx = useContext(AppDataContext);
  if (!ctx) throw new Error('useAppData must be used within AppDataProvider');
  return ctx;
};

interface AppDataProviderProps {
  children: React.ReactNode;
  enabled?: boolean;
}

export const AppDataProvider: React.FC<AppDataProviderProps> = ({ children, enabled = true }) => {
  const { setLoading } = useLoading();
  const [calendarData, setCalendarData] = useState<DayDataRecord>({});
  const [monthStartDay, setMonthStartDay] = useState<number>(1);
  const [isReady, setIsReady] = useState<boolean>(false);
  const [dataVersion, setDataVersion] = useState<number>(0);
  const refreshingRef = useRef(false);
  const initializedRef = useRef(false);

  const refresh = useCallback(async () => {
    if (refreshingRef.current) {
      return;
    }
    refreshingRef.current = true;
    setLoading(true);
    try {
      const [storedData, msd, allCategories] = await Promise.all([
        AsyncStorage.getItem('calendarData'),
        loadMonthStartDay(),
        loadAllCategories(),
      ]);
      
      // AsyncStorage에서 기존 데이터 로드 (수입, 챌린지 등)
      const localCalendarData = storedData ? JSON.parse(storedData) : {};

      // 현재 존재하는 카테고리 이름 집합 생성
      const validCategoryLabels = new Set(allCategories.map(cat => cat.label));

      // 로컬 데이터에서 삭제된 레코드 및 삭제된 카테고리 레코드 제거 및 총액 재계산
      Object.keys(localCalendarData).forEach(dateKey => {
        const bucket = localCalendarData[dateKey];
        if (!bucket || !Array.isArray(bucket.records)) {
          delete localCalendarData[dateKey];
          return;
        }

        bucket.records = bucket.records.filter((record: any) => {
          // isDeleted가 true인 레코드 제거
          if (record?.isDeleted === true) {
            return false;
          }
          
          // 삭제된 카테고리의 지출/수입 레코드 제거
          if (
            (record?.type === 'expense' || record?.type === 'income') &&
            record?.category &&
            !validCategoryLabels.has(record.category)
          ) {
            return false;
          }
          
          return true;
        });

        let totalExpense = 0;
        let totalIncome = 0;
        bucket.records.forEach((record: any) => {
          if (record?.type === 'expense' && record?.isRefunded !== true) {
            totalExpense += record?.amount || 0;
          } else if (record?.type === 'income') {
            totalIncome += record?.amount || 0;
          }
        });

        bucket.totalExpense = totalExpense;
        bucket.totalIncome = totalIncome;

        if (bucket.records.length === 0 && totalIncome === 0) {
          delete localCalendarData[dateKey];
        }
      });
      
      // 저장된 지출/수입 기록 조회
      let fetchedCalendarData: DayDataRecord = {};
      try {
        const [expenses, incomes] = await Promise.all([
          getAllExpenses(),
          getAllIncomes(),
        ]);

        // 지출 기록을 calendarData 구조로 변환
        expenses.forEach((expense: ExpenseRecord) => {
          if (expense.isDeleted) {
            return;
          }

          // 날짜 형식 변환: YYYY.MM.DD → YYYY-MM-DD
          const dateKey = expense.date.replace(/\./g, '-');
          
          // 날짜별 데이터 구조 생성
          if (!fetchedCalendarData[dateKey]) {
            fetchedCalendarData[dateKey] = {
              totalExpense: 0,
              totalIncome: 0,
              records: [],
            };
          }
          
          // 지출 기록 추가
          fetchedCalendarData[dateKey].records.push({
            type: 'expense',
            amount: expense.amount,
            category: expense.category,
            memo: expense.memo,
            date: expense.date,
            timestamp: expense.timestamp,
            isRecurring: expense.isRecurring,
            weekendOption: expense.weekendOption,
            recurringType: expense.recurringType,
            recurringId: expense.recurringId,
            installmentId: expense.installmentId,
            isAutoGenerated: expense.isAutoGenerated,
            isInstallment: expense.isInstallment,
            totalMonths: expense.totalMonths,
            installmentMonths: expense.installmentMonths,
            originalInstallment: expense.originalInstallment,
            isPrepaid: expense.isPrepaid,
            prepaidDate: expense.prepaidDate,
            isRefunded: expense.isRefunded,
            originalAmountBeforeRefund: expense.originalAmountBeforeRefund,
            originalAmount: expense.originalAmount,
            originalCategory: expense.originalCategory,
            originalDate: expense.originalDate,
            isDeleted: expense.isDeleted,
            deletedAt: expense.deletedAt,
          });
          
          // 총액 계산 (환불된 기록은 제외)
          if (!expense.isRefunded) {
            fetchedCalendarData[dateKey].totalExpense += expense.amount || 0;
          }
        });
        
        // 수입 기록 병합
        incomes.forEach((income: IncomeRecord) => {
          if (income.isDeleted) {
            return;
          }

          const dateKey = income.date.replace(/\./g, '-');

          if (!fetchedCalendarData[dateKey]) {
            fetchedCalendarData[dateKey] = {
              totalExpense: 0,
              totalIncome: 0,
              records: [],
            };
          }

          fetchedCalendarData[dateKey].records.push({
            type: 'income',
            amount: income.amount,
            category: income.category ?? '수입',
            memo: income.memo,
            date: income.date,
            timestamp: income.timestamp,
            isDeleted: income.isDeleted,
            deletedAt: income.deletedAt,
          });

          fetchedCalendarData[dateKey].totalIncome += income.amount || 0;
        });
        
        // 각 날짜별 총액 재계산 (기록이 모두 추가된 후)
        Object.keys(fetchedCalendarData).forEach(dateKey => {
          let totalExpense = 0;
          let totalIncome = 0;
          fetchedCalendarData[dateKey].records.forEach((record: any) => {
            if (record.type === 'expense' && record.isDeleted !== true && !record.isRefunded) {
              totalExpense += record.amount || 0;
            } else if (record.type === 'income' && record.isDeleted !== true) {
              totalIncome += record.amount || 0;
            }
          });
          fetchedCalendarData[dateKey].totalExpense = totalExpense;
          fetchedCalendarData[dateKey].totalIncome = totalIncome;
        });
      } catch (error) {
        console.error('[app-data-context] Failed to load expenses/incomes:', error);
        // 로드 실패 시 AsyncStorage 데이터만 사용
      }
      
      // 조회한 데이터와 AsyncStorage 데이터 병합
      // 조회 결과를 우선하고, AsyncStorage에만 있는 기록은 유지
      const mergedCalendarData: DayDataRecord = { ...localCalendarData };
      
      Object.keys(fetchedCalendarData).forEach(dateKey => {
        if (mergedCalendarData[dateKey]) {
          const existingRecords = mergedCalendarData[dateKey].records || [];
          const fetchedRecords = fetchedCalendarData[dateKey].records || [];

          const fetchedIncomeTimestamps = new Set(
            fetchedRecords
              .filter((record: any) => record.type === 'income')
              .map((record: any) => record.timestamp)
          );

          const fetchedExpenseTimestamps = new Set(
            fetchedRecords
              .filter((record: any) => record.type === 'expense')
              .map((record: any) => record.timestamp)
          );

          const remainingLocalRecords = existingRecords.filter((record: any) => {
            if (record.isDeleted) {
              return false;
            }

            // 삭제된 카테고리의 지출/수입 레코드 제거
            if (
              (record.type === 'expense' || record.type === 'income') &&
              record.category &&
              !validCategoryLabels.has(record.category)
            ) {
              return false;
            }

            if (record.type === 'income') {
              return !fetchedIncomeTimestamps.has(record.timestamp);
            }

            if (record.type === 'expense') {
              return !fetchedExpenseTimestamps.has(record.timestamp);
            }

            return true;
          });

          mergedCalendarData[dateKey] = {
            totalExpense: fetchedCalendarData[dateKey].totalExpense,
            totalIncome:
              fetchedCalendarData[dateKey].totalIncome +
              remainingLocalRecords
                .filter((record: any) => record.type === 'income')
                .reduce((sum: number, record: any) => sum + (record.amount || 0), 0),
            records: [...fetchedRecords, ...remainingLocalRecords],
          };
        } else {
          // 새로운 날짜 데이터는 조회 데이터 그대로 사용
          mergedCalendarData[dateKey] = fetchedCalendarData[dateKey];
        }
      });
      
      // 최종 정리: 삭제된 카테고리 레코드 제거, 총액 재계산, 잔재 제거
      Object.keys(mergedCalendarData).forEach((dateKey) => {
        const bucket = mergedCalendarData[dateKey];
        if (!bucket || !Array.isArray(bucket.records)) {
          delete mergedCalendarData[dateKey];
          return;
        }

        // 삭제된 카테고리의 지출/수입 레코드 제거
        const originalLength = bucket.records.length;
        bucket.records = bucket.records.filter((record: any) => {
          if (
            (record?.type === 'expense' || record?.type === 'income') &&
            record?.category &&
            !validCategoryLabels.has(record.category)
          ) {
            return false;
          }
          return true;
        });

        // 총액 재계산 (삭제된 레코드가 있을 경우)
        if (bucket.records.length !== originalLength) {
          let totalExpense = 0;
          let totalIncome = 0;
          bucket.records.forEach((record: any) => {
            if (record?.type === 'expense' && record?.isRefunded !== true) {
              totalExpense += record?.amount || 0;
            } else if (record?.type === 'income') {
              totalIncome += record?.amount || 0;
            }
          });
          bucket.totalExpense = totalExpense;
          bucket.totalIncome = totalIncome;
        }

        // 기록이 없고 총액이 0인 날짜 키 삭제
        if (bucket.records.length === 0 && bucket.totalIncome === 0 && bucket.totalExpense === 0) {
          delete mergedCalendarData[dateKey];
        }
      });
      
      // 필터링된 데이터를 AsyncStorage에 저장 (삭제된 카테고리 레코드 제거 반영)
      try {
        await AsyncStorage.setItem('calendarData', JSON.stringify(mergedCalendarData));
      } catch (error) {
        console.error('[app-data-context] Failed to save filtered calendar data:', error);
      }
      
      setCalendarData(mergedCalendarData);
      setMonthStartDay(msd);
      setIsReady(true);
      setDataVersion((v) => v + 1);
    } finally {
      refreshingRef.current = false;
      setLoading(false);
    }
  }, [setLoading]);

  useEffect(() => {
    if (!enabled || initializedRef.current) {
      return;
    }
    initializedRef.current = true;
    refresh().catch(() => {});
  }, [enabled, refresh]);

  useEffect(() => {
    const unsub = monthStartEvent.subscribe((day) => {
      setMonthStartDay(day);
      // 월 시작일이 바뀌면 버전만 증가(데이터는 그대로일 수 있음)
      setDataVersion((v) => v + 1);
    });
    return unsub;
  }, []);

  const value = useMemo(
    () => ({ calendarData, monthStartDay, refresh, isReady, dataVersion }),
    [calendarData, monthStartDay, refresh, isReady, dataVersion]
  );

  return (
    <AppDataContext.Provider value={value}>
      {children}
    </AppDataContext.Provider>
  );
};


