import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useLoading } from '@/contexts/loading-context';
import { loadMonthStartDay, monthStartEvent } from '@/hooks/use-month-start';
import { getAllExpenses, type ExpenseRecord } from '@/utils/expenses';
import { getAllIncomes } from '@/utils/incomes';

export interface DayDataRecord {
  [date: string]: any;
}

interface AppDataContextType {
  calendarData: DayDataRecord;
  monthStartDay: number;
  refresh: () => Promise<void>;
  isReady: boolean;
  dataVersion: number;
}

const AppDataContext = createContext<AppDataContextType | undefined>(undefined);

export const useAppData = (): AppDataContextType => {
  const ctx = useContext(AppDataContext);
  if (!ctx) throw new Error('useAppData must be used within AppDataProvider');
  return ctx;
};

export const AppDataProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { setLoading } = useLoading();
  const [calendarData, setCalendarData] = useState<DayDataRecord>({});
  const [monthStartDay, setMonthStartDay] = useState<number>(1);
  const [isReady, setIsReady] = useState<boolean>(false);
  const [dataVersion, setDataVersion] = useState<number>(0);

  const refresh = async () => {
    setLoading(true);
    try {
      const [storedData, msd] = await Promise.all([
        AsyncStorage.getItem('calendarData'),
        loadMonthStartDay(),
      ]);
      
      // AsyncStorage에서 기존 데이터 로드 (입금, 챌린지 등)
      const localCalendarData = storedData ? JSON.parse(storedData) : {};

      // 로컬 데이터에서 삭제된 레코드 제거 및 총액 재계산
      Object.keys(localCalendarData).forEach(dateKey => {
        const bucket = localCalendarData[dateKey];
        if (!bucket || !Array.isArray(bucket.records)) {
          delete localCalendarData[dateKey];
          return;
        }

        bucket.records = bucket.records.filter((record: any) => record?.isDeleted !== true);

        let totalExpense = 0;
        let totalIncome = 0;
        bucket.records.forEach((record: any) => {
          if (record?.type === 'expense' && record?.isRefunded !== true) {
            totalExpense += record?.amount || 0;
          } else if (record?.type === 'income') {
            totalIncome += record?.amount || 0;
          }
        });

        bucket.totalExpense = totalExpense;
        bucket.totalIncome = totalIncome;

        if (bucket.records.length === 0 && totalIncome === 0) {
          delete localCalendarData[dateKey];
        }
      });
      
      // Supabase에서 지출/입금 기록 조회
      let supabaseCalendarData: DayDataRecord = {};
      try {
        const [expenses, incomes] = await Promise.all([
          getAllExpenses(),
          getAllIncomes(),
        ]);
        
        // Supabase 지출 기록을 calendarData 구조로 변환
        expenses.forEach((expense: ExpenseRecord) => {
          if (expense.isDeleted) {
            return;
          }

          // 날짜 형식 변환: YYYY.MM.DD → YYYY-MM-DD
          const dateKey = expense.date.replace(/\./g, '-');
          
          // 날짜별 데이터 구조 생성
          if (!supabaseCalendarData[dateKey]) {
            supabaseCalendarData[dateKey] = {
              totalExpense: 0,
              totalIncome: 0,
              records: [],
            };
          }
          
          // 지출 기록 추가
          supabaseCalendarData[dateKey].records.push({
            type: 'expense',
            amount: expense.amount,
            category: expense.category,
            memo: expense.memo,
            date: expense.date,
            timestamp: expense.timestamp,
            isRecurring: expense.isRecurring,
            weekendOption: expense.weekendOption,
            recurringId: expense.recurringId,
            installmentId: expense.installmentId,
            isAutoGenerated: expense.isAutoGenerated,
            isInstallment: expense.isInstallment,
            totalMonths: expense.totalMonths,
            installmentMonths: expense.installmentMonths,
            originalInstallment: expense.originalInstallment,
            isPrepaid: expense.isPrepaid,
            prepaidDate: expense.prepaidDate,
            isRefunded: expense.isRefunded,
            originalAmount: expense.originalAmount,
            originalCategory: expense.originalCategory,
            originalDate: expense.originalDate,
            isDeleted: expense.isDeleted,
            deletedAt: expense.deletedAt,
          });
          
          // 총액 계산 (환불된 기록은 제외)
          if (!expense.isRefunded) {
            supabaseCalendarData[dateKey].totalExpense += expense.amount || 0;
          }
        });
        
        // Supabase 입금 기록 병합
        incomes.forEach((income: IncomeRecord) => {
          if (income.isDeleted) {
            return;
          }

          const dateKey = income.date.replace(/\./g, '-');

          if (!supabaseCalendarData[dateKey]) {
            supabaseCalendarData[dateKey] = {
              totalExpense: 0,
              totalIncome: 0,
              records: [],
            };
          }

          supabaseCalendarData[dateKey].records.push({
            type: 'income',
            amount: income.amount,
            category: '💰 입금',
            memo: income.memo,
            date: income.date,
            timestamp: income.timestamp,
            isDeleted: income.isDeleted,
            deletedAt: income.deletedAt,
          });

          supabaseCalendarData[dateKey].totalIncome += income.amount || 0;
        });
        
        // 각 날짜별 총액 재계산 (기록이 모두 추가된 후)
        Object.keys(supabaseCalendarData).forEach(dateKey => {
          let totalExpense = 0;
          let totalIncome = 0;
          supabaseCalendarData[dateKey].records.forEach((record: any) => {
            if (record.type === 'expense' && record.isDeleted !== true && !record.isRefunded) {
              totalExpense += record.amount || 0;
            } else if (record.type === 'income' && record.isDeleted !== true) {
              totalIncome += record.amount || 0;
            }
          });
          supabaseCalendarData[dateKey].totalExpense = totalExpense;
          supabaseCalendarData[dateKey].totalIncome = totalIncome;
        });
        
        console.log('[app-data-context] Loaded expenses from Supabase:', expenses.length);
        console.log('[app-data-context] Loaded incomes from Supabase:', incomes.length);
      } catch (error) {
        console.error('[app-data-context] Failed to load expenses/incomes from Supabase:', error);
        // Supabase 로드 실패 시 AsyncStorage 데이터만 사용
      }
      
      // Supabase 데이터와 AsyncStorage 데이터 병합
      // Supabase의 지출/입금 기록을 우선하고, AsyncStorage에만 있는 기록은 유지
      const mergedCalendarData: DayDataRecord = { ...localCalendarData };
      
      Object.keys(supabaseCalendarData).forEach(dateKey => {
        if (mergedCalendarData[dateKey]) {
          const existingRecords = mergedCalendarData[dateKey].records || [];
          const supabaseRecords = supabaseCalendarData[dateKey].records || [];

          const supabaseIncomeTimestamps = new Set(
            supabaseRecords
              .filter((record: any) => record.type === 'income')
              .map((record: any) => record.timestamp)
          );

          const supabaseExpenseTimestamps = new Set(
            supabaseRecords
              .filter((record: any) => record.type === 'expense')
              .map((record: any) => record.timestamp)
          );

          const remainingLocalRecords = existingRecords.filter((record: any) => {
            if (record.isDeleted) {
              return false;
            }

            if (record.type === 'income') {
              return !supabaseIncomeTimestamps.has(record.timestamp);
            }

            if (record.type === 'expense') {
              return !supabaseExpenseTimestamps.has(record.timestamp);
            }

            return true;
          });

          mergedCalendarData[dateKey] = {
            totalExpense: supabaseCalendarData[dateKey].totalExpense,
            totalIncome:
              supabaseCalendarData[dateKey].totalIncome +
              remainingLocalRecords
                .filter((record: any) => record.type === 'income')
                .reduce((sum: number, record: any) => sum + (record.amount || 0), 0),
            records: [...supabaseRecords, ...remainingLocalRecords],
          };
        } else {
          // 새로운 날짜 데이터는 Supabase 데이터 그대로 사용
          mergedCalendarData[dateKey] = supabaseCalendarData[dateKey];
        }
      });
      
      setCalendarData(mergedCalendarData);
      setMonthStartDay(msd);
      setIsReady(true);
      setDataVersion((v) => v + 1);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    refresh().catch(() => {});
  }, []);

  useEffect(() => {
    const unsub = monthStartEvent.subscribe((day) => {
      setMonthStartDay(day);
      // 월 시작일이 바뀌면 버전만 증가(데이터는 그대로일 수 있음)
      setDataVersion((v) => v + 1);
    });
    return unsub;
  }, []);

  const value = useMemo(() => ({ calendarData, monthStartDay, refresh, isReady, dataVersion }), [calendarData, monthStartDay, isReady, dataVersion]);

  return (
    <AppDataContext.Provider value={value}>
      {children}
    </AppDataContext.Provider>
  );
};


