/**
 * Monthly Expense Timeline Screen
 * 
 * Shows timeline of expenses and income for a selected month.
 */

import { TopNavigation } from '@/components/navigation/top-navigation';
import { Tab } from '@/components/ui/tab';
import { Tag } from '@/components/ui/tag';
import { Colors, Typography } from '@/constants/theme';
import { useColorScheme } from '@/hooks/use-color-scheme';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

interface TimelineItem {
  date: string; // YYYY-MM-DD
  type: 'income' | 'expense';
  category: string;
  memo?: string;
  amount: number;
  timestamp?: number;
  isRecurring?: boolean;
  weekendOption?: 'friday' | 'monday';
  isPrepaid?: boolean;
  recurringId?: string;
  isAutoGenerated?: boolean;
  actualRecordIndex?: number; // 실제 데이터의 recordIndex
  isAmountSplit?: boolean; // 금액 분할 여부
  originalAmountSplit?: boolean; // 최초 생성 시 금액 분할 설정
  recurringMonths?: number; // 정기 기록 개월 수
}

// 카테고리 이모지 매핑
const CATEGORY_EMOJIS: Record<string, string> = {
  '식비': '🍚',
  '배달음식': '🛵',
  '카페/편의점/간식': '☕️',
  '교통비': '🚊',
  '주거비': '🏠',
  '공과금': '📎',
  '통신비': '☎️',
  '쇼핑': '🛍️',
  '미용': '💇🏻‍♂️',
  '운동/헬스': '💪',
  '구독 서비스': '📌',
  '영화': '🎬',
  '취미': '👨🏻‍💻',
  '여행': '🧳',
  '모임/술': '🍺',
  '경조사/선물': '🎁',
  '차량': '🚘',
  '대출/이자': '🏦',
  '보험': '🔖',
  '적금': '💵',
  '투자': '📈',
  '세금': '⚖️',
  '기타': '📝',
};

export default function MonthlyExpenseTimelineScreen() {
  const colorScheme = useColorScheme();
  const colors = Colors[colorScheme ?? 'light'] as typeof Colors.light;
  const router = useRouter();
  
  // 화면 진입 시에만 로그 출력
  useEffect(() => {
    console.log('📍 [화면] 월 소비현황 - 타임라인');
  }, []);

  // Year/Month options for picker
  const yearOptions = useMemo(() => {
    const currentYear = new Date().getFullYear();
    const years = [];
    for (let i = currentYear - 5; i <= currentYear + 1; i++) {
      years.push({ label: `${i}년`, value: i });
    }
    return years;
  }, []);

  const monthOptions = useMemo(() => {
    const months = [];
    for (let i = 1; i <= 12; i++) {
      months.push({ label: `${i}월`, value: i });
    }
    return months;
  }, []);
  
  // Params from home screen
  const params = useLocalSearchParams<{
    year?: string;
    month?: string;
    selectedDate?: string;
  }>();
  
  const year = params.year ? parseInt(params.year) : new Date().getFullYear();
  const month = params.month ? parseInt(params.month) : new Date().getMonth() + 1;
  
  // Tab state
  const [activeTab, setActiveTab] = useState('timeline');
  
  // Timeline data
  const [timelineData, setTimelineData] = useState<TimelineItem[]>([]);
  
  // Load calendar data from AsyncStorage
  useEffect(() => {
    const loadTimelineData = async () => {
      try {
        const storedData = await AsyncStorage.getItem('calendarData');
        if (storedData) {
          const calendarData = JSON.parse(storedData);
          
          // Convert calendar data to timeline items
          const items: TimelineItem[] = [];
          
          Object.entries(calendarData).forEach(([dateString, data]: [string, any]) => {
            const date = new Date(dateString);
            const itemYear = date.getFullYear();
            const itemMonth = date.getMonth() + 1;
            
            // Only include data for the selected year/month
            if (itemYear === year && itemMonth === month) {
              // records 배열에서 건별 기록 가져오기
              if (data.records && Array.isArray(data.records)) {
                data.records.forEach((record: any, recordIndex: number) => {
                  items.push({
                    date: dateString,
                    type: record.type,
                    category: record.category,
                    memo: record.memo,
                    amount: record.amount,
                    timestamp: record.timestamp,
                    isRecurring: record.isRecurring,
                    weekendOption: record.weekendOption,
                    recurringId: record.recurringId,
                    isAutoGenerated: record.isAutoGenerated,
                    isPrepaid: record.isPrepaid,
                    // 실제 데이터의 recordIndex 저장
                    actualRecordIndex: recordIndex,
                    // 분할 기록 관련 정보 추가
                    isAmountSplit: record.isAmountSplit,
                    originalAmountSplit: record.originalAmountSplit,
                    recurringMonths: record.recurringMonths,
                  });
                });
              }
            }
          });
          
          // Sort by date (newest first), then by timestamp within same date
          items.sort((a, b) => {
            const dateCompare = new Date(b.date).getTime() - new Date(a.date).getTime();
            if (dateCompare !== 0) return dateCompare;
            // 같은 날짜면 timestamp로 정렬 (최신 기록이 위)
            return (b.timestamp || 0) - (a.timestamp || 0);
          });
          
          
          setTimelineData(items);
        }
      } catch (error) {
        console.error('Failed to load timeline data:', error);
      }
    };
    
    loadTimelineData();
  }, [year, month]);
  
  // Calculate monthly totals
  const monthlyTotals = useMemo(() => {
    let income = 0;
    let expense = 0;
    
    timelineData.forEach((item) => {
      if (item.type === 'income') {
        income += item.amount;
      } else {
        expense += item.amount;
      }
    });
    
    return { income, expense };
  }, [timelineData]);
  
  // Group timeline items by date
  const groupedTimeline = useMemo(() => {
    const groups: Record<string, TimelineItem[]> = {};
    
    timelineData.forEach((item) => {
      if (!groups[item.date]) {
        groups[item.date] = [];
      }
      groups[item.date].push(item);
    });
    
    return groups;
  }, [timelineData]);
  
  // Format date for display
  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}.${month}.${day}`;
  };
  
  const handleBackPress = useCallback(() => {
    router.back();
  }, [router]);
  
  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]} edges={['top', 'bottom']}>
      {/* Top Navigation */}
      <TopNavigation
        type="sub"
        title=""
        showDay
        dateText={`${year}년 ${String(month).padStart(2, '0')}월`}
        showLeftIcon
        onLeftIconPress={handleBackPress}
        showDropdownArrow
        yearOptions={yearOptions}
        selectedYear={year}
        onYearChange={(newYear) => {
          router.push({
            pathname: '/monthly-expense-timeline',
            params: { year: newYear.toString(), month: month.toString() }
          });
        }}
        monthOptions={monthOptions}
        selectedMonth={month}
        onMonthChange={(newMonth) => {
          router.push({
            pathname: '/monthly-expense-timeline',
            params: { year: year.toString(), month: newMonth.toString() }
          });
        }}
      />
      
      {/* Tab Menu */}
      <Tab
        options={[
          { label: '타임라인', value: 'timeline' },
          { label: '소비 현황', value: 'status' },
          { label: '챌린지 현황', value: 'challenge' },
        ]}
        value={activeTab}
        onValueChange={setActiveTab}
      />
      
      {/* Month Summary */}
      <View style={[styles.summaryContainer, { backgroundColor: colors.background }]}>
        <Text style={[styles.summaryMonth, { color: colors.staticBlack }]}>
          {year}년 {String(month).padStart(2, '0')}월
        </Text>
        
        <View style={styles.summaryAmounts}>
          <View style={styles.summaryIncomeContainer}>
            <Text 
              style={[styles.summaryIncome, { color: colors.text }]}
              adjustsFontSizeToFit
              numberOfLines={1}
              minimumFontScale={0.7}
            >
              + {monthlyTotals.income.toLocaleString()}원
            </Text>
          </View>
          
          <View style={[styles.summaryDivider, { backgroundColor: colors.border }]} />
          
          <View style={styles.summaryExpenseContainer}>
            <Text 
              style={[styles.summaryExpense, { color: colors.text }]}
              adjustsFontSizeToFit
              numberOfLines={1}
              minimumFontScale={0.7}
            >
              - {monthlyTotals.expense.toLocaleString()}원
            </Text>
          </View>
        </View>
      </View>
      
      {/* Divider */}
      <View style={styles.headerDivider} />
      
      {/* Timeline Content */}
      <ScrollView 
        style={styles.scrollContainer}
        contentContainerStyle={styles.scrollContent}
      >
        {Object.keys(groupedTimeline).length === 0 ? (
          <View style={styles.emptyContainer}>
            <Text style={[styles.emptyText, { color: colors.textAssistive }]}>
              이 달의 기록이 없습니다.
            </Text>
          </View>
        ) : (
          Object.entries(groupedTimeline).map(([date, items], groupIndex) => {
            const totalGroups = Object.keys(groupedTimeline).length;
            const isLastGroup = groupIndex === totalGroups - 1;
            
            return (
              <View key={date} style={styles.dateGroup}>
                {items.map((item, itemIndex) => {
                  const isFirstInGroup = itemIndex === 0;
                  const isLastInGroup = itemIndex === items.length - 1;
                  
                  return (
                    <View key={`${date}-${itemIndex}`}>
                      <Pressable 
                        style={styles.timelineItem}
                        onPress={async () => {
                          console.log('🔍 [타임라인] 항목 클릭:', {
                            itemType: item.type,
                            category: item.category,
                            amount: item.amount,
                            date: date,
                            itemIndex: itemIndex,
                            actualRecordIndex: item.actualRecordIndex
                          });
                          
                          if (item.type === 'expense') {
                            console.log('📝 [타임라인] 소비 기록 수정화면으로 이동 시도');
                            
                            // 실제 데이터에서 정확한 recordIndex 찾기
                            let correctRecordIndex = item.actualRecordIndex || 0;
                            
                            try {
                              const storedData = await AsyncStorage.getItem('calendarData');
                              if (storedData) {
                                const calendarData = JSON.parse(storedData);
                                const dateRecords = calendarData[date]?.records || [];
                                
                                console.log('🔍 [타임라인] 실제 데이터 검색:', {
                                  date: date,
                                  totalRecords: dateRecords.length,
                                  targetItem: {
                                    timestamp: item.timestamp,
                                    category: item.category,
                                    amount: item.amount
                                  }
                                });
                                
                                // 실제 데이터의 모든 기록 로그
                                dateRecords.forEach((record: any, index: number) => {
                                  console.log(`📋 [타임라인] 실제 기록 ${index}:`, {
                                    timestamp: record.timestamp,
                                    category: record.category,
                                    amount: record.amount,
                                    date: record.date
                                  });
                                });
                                
                                // timestamp와 category, amount로 정확한 인덱스 찾기
                                const foundIndex = dateRecords.findIndex((record: any) => 
                                  record.timestamp === item.timestamp &&
                                  record.category === item.category &&
                                  record.amount === item.amount
                                );
                                
                                console.log('🔍 [타임라인] 인덱스 검색 결과:', {
                                  foundIndex: foundIndex,
                                  targetTimestamp: item.timestamp,
                                  targetCategory: item.category,
                                  targetAmount: item.amount
                                });
                                
                                if (foundIndex !== -1) {
                                  correctRecordIndex = foundIndex;
                                  console.log('✅ [타임라인] 정확한 recordIndex 찾음:', {
                                    original: item.actualRecordIndex,
                                    correct: correctRecordIndex
                                  });
                                } else {
                                  console.log('⚠️ [타임라인] 정확한 recordIndex를 찾지 못함, 기본값 사용:', correctRecordIndex);
                                  
                                  // 대안: category와 amount만으로 찾기
                                  const fallbackIndex = dateRecords.findIndex((record: any) => 
                                    record.category === item.category &&
                                    record.amount === item.amount
                                  );
                                  
                                  if (fallbackIndex !== -1) {
                                    correctRecordIndex = fallbackIndex;
                                    console.log('🔄 [타임라인] 대안 방법으로 recordIndex 찾음:', {
                                      fallbackIndex: fallbackIndex,
                                      category: item.category,
                                      amount: item.amount
                                    });
                                  }
                                }
                              }
                            } catch (error) {
                              console.error('❌ [타임라인] recordIndex 계산 오류:', error);
                            }
                            
                            console.log('📊 [타임라인] 전달할 데이터:', {
                              recordData: item,
                              dateKey: date,
                              recordIndex: correctRecordIndex
                            });
                            
                            // 소비 기록인 경우 수정화면으로 이동
                            router.push({
                              pathname: '/expense-edit',
                              params: {
                                recordData: JSON.stringify(item),
                                dateKey: date,
                                recordIndex: correctRecordIndex.toString(),
                              },
                            });
                            
                            console.log('✅ [타임라인] router.push 호출 완료');
                          } else {
                            console.log('ℹ️ [타임라인] 입금 기록이므로 수정 불가');
                          }
                        }}
                      >
                        {/* Date Column */}
                        <View style={styles.dateColumn}>
                          {isFirstInGroup && (
                            <Text style={[styles.dateText, { color: colors.textAssistive }]}>
                              {formatDate(date)}
                            </Text>
                          )}
                        </View>
                        
                        {/* Content: Category/Amount + Memo */}
                        <View style={styles.itemContent}>
                          {/* Category and Amount */}
                          <View style={styles.itemRow1}>
                            <View style={styles.categoryContainer}>
                              <Text 
                                style={[styles.categoryText, { color: colors.text }]}
                              >
                                {item.type === 'expense' && CATEGORY_EMOJIS[item.category]
                                  ? `${CATEGORY_EMOJIS[item.category]} ${item.category}`
                                  : item.category}
                              </Text>
                            </View>
                            <View style={styles.amountContainer}>
                              <Text 
                                style={[styles.amountText, { color: colors.text }]}
                                adjustsFontSizeToFit
                                numberOfLines={1}
                                minimumFontScale={0.7}
                              >
                                {item.amount.toLocaleString()}원
                              </Text>
                            </View>
                          </View>
                          
                          {/* Memo */}
                          <View style={styles.itemRow2}>
                            <View style={styles.memoContainer}>
                              <Text
                                style={[styles.memoText, { color: colors.textAssistive }]}
                              >
                                {item.memo ? item.memo.replace(/\n/g, ' ') : ' '}
                              </Text>
                              {/* 태그 표시 */}
                              {item.isPrepaid && (
                                <Tag label="선납" status="positive" />
                              )}
                              {item.isRecurring && !item.isPrepaid && (
                                <Tag label="정기" status="normal" />
                              )}
                            </View>
                          </View>
                        </View>
                      </Pressable>
                      
                      {/* Item Divider - 자식 리스트 하단 */}
                      {!isLastInGroup && (
                        <View style={[styles.itemDivider, { backgroundColor: colors.border }]} />
                      )}
                    </View>
                  );
                })}
                
                {/* Date Group Divider */}
                {!isLastGroup && (
                  <View style={[styles.dateGroupDivider, { backgroundColor: colors.border }]} />
                )}
              </View>
            );
          })
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  summaryContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  summaryMonth: {
    ...Typography.body1.l.bold,
  },
  summaryAmounts: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    justifyContent: 'flex-end',
  },
  summaryIncomeContainer: {
    flexShrink: 1,
    alignItems: 'center',
  },
  summaryIncome: {
    ...Typography.body1.l.bold,
  },
  summaryDivider: {
    width: 1,
    height: 8,
  },
  summaryExpenseContainer: {
    flexShrink: 1,
    alignItems: 'center',
  },
  summaryExpense: {
    ...Typography.body1.l.bold,
  },
  headerDivider: {
    height: 8,
    width: '100%',
    backgroundColor: 'rgba(144, 146, 158, 0.1)',
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 0, // 내용물 크기만큼만, 늘어나지 않음
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 80,
  },
  emptyText: {
    ...Typography.body1.l.regular,
  },
  dateGroup: {
    // No padding - handled by individual items
  },
  timelineItem: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16, // 상하 패딩 16px
    // height 제거 - 내용에 따라 자동 조정
  },
  timelineItemWithDivider: {
    borderBottomWidth: 1,
    borderBottomColor: 'transparent', // 기본값, 동적으로 설정됨
    marginHorizontal: 16, // 좌우 여백 추가
  },
  dateColumn: {
    width: 94,
  },
  dateText: {
    ...Typography.body1.l.medium,
  },
  itemContent: {
    flex: 1,
    flexDirection: 'column',
    gap: 4,
  },
  itemRow1: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  itemRow2: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  categoryContainer: {
    flex: 6,
  },
  categoryText: {
    ...Typography.body1.l.bold,
    lineHeight: 24,
  },
  amountContainer: {
    flex: 4,
    alignItems: 'flex-end',
  },
  amountText: {
    ...Typography.body1.l.bold,
    textAlign: 'right',
  },
  memoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  memoText: {
    ...Typography.body2.r.regular,
    lineHeight: 21,
    flex: 1,
  },
  itemDivider: {
    height: 1,
    marginLeft: 110, // 16 + 94 = padding + date column width
    marginTop: 0,    // 상단 여백 0
    marginBottom: 0, // 하단 여백 0
  },
  dateGroupDivider: {
    height: 1,
    width: '100%',        // 가로값 100%
    marginTop: 0,         // 상단 여백 제거
    marginBottom: 0,      // 하단 여백 제거
    marginHorizontal: 16, // 양옆 여백 유지
  },
});

