/**
 * Monthly Expense Timeline Screen
 * 
 * Shows timeline of expenses and income for a selected month.
 */

import { TopNavigation } from '@/components/navigation/top-navigation';
import { Chip } from '@/components/ui/chip';
import { Tab } from '@/components/ui/tab';
import { Tag } from '@/components/ui/tag';
import { Colors, Typography } from '@/constants/theme';
import { useAppData } from '@/contexts/app-data-context';
import { useLoading } from '@/contexts/loading-context';
import { useColorScheme } from '@/hooks/use-color-scheme';
import { loadMonthStartDay } from '@/hooks/use-month-start';
import { applyPendingCalendarTargetEvent, setLatestPendingCalendarTarget } from '@/hooks/calendar-events';
import { loadCategories } from '@/utils/categories';
import { getCustomMonthRange, isDateInCustomMonth } from '@/utils/custom-month';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Animated, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

// 카테고리별 이모지 매핑 (통합 카테고리 로드)
const useCategoryEmojiMap = () => {
  const [map, setMap] = useState<Record<string, string>>({});

  useEffect(() => {
    Promise.all([loadCategories('expense'), loadCategories('income')])
      .then(([expense, income]) => {
        const next: Record<string, string> = {};
        [...expense, ...income].forEach((c) => {
          next[c.label] = c.emoji;
        });
        setMap(next);
      })
      .catch(() => {
        // 로드 실패 시 빈 맵 유지
      });
  }, []);

  return map;
};

interface TimelineItem {
  id?: string;
  date: string; // YYYY-MM-DD
  type: 'income' | 'expense';
  category: string;
  memo?: string;
  amount: number;
  timestamp?: number;
  isRecurring?: boolean;
  weekendOption?: 'friday' | 'monday';
  recurringType?: string; // 정기 기록 반복 타입 (매일, 매주, 2주, 3주, 4주, 매월, 2개월 마다, 4개월 마다, 6개월 마다, 주중, 주말)
  isPrepaid?: boolean;
  prepaidDate?: string; // 선결제 처리 날짜
  recurringId?: string;
  installmentId?: string; // 할부 기록 ID
  installmentOriginDate?: string; // 원래 할부 예정일 (선결제 기록용)
  originalDate?: string; // 최초 생성일 (레거시 데이터 용)
  isAutoGenerated?: boolean;
  actualRecordIndex?: number; // 실제 데이터의 recordIndex
  isInstallment?: boolean; // 할부 여부
  originalInstallment?: boolean; // 최초 생성 시 할부 설정
  totalMonths?: number; // 정기 기록 개월 수
  isRefunded?: boolean; // 환불 여부
  isSettled?: boolean; // 결산 여부
  settledAt?: string; // 결산 처리 날짜
  originalAmountBeforeSettlement?: number; // 결산 전 원금
}

interface ChallengeData {
  id: string;
  category: string;
  startDate: string; // YYYY.MM.DD
  endDate: string; // YYYY.MM.DD
  targetAmount: number;
  createdAt: number;
  recurringId: string; // 반복 챌린지의 그룹 ID
}

export default function MonthlyExpenseTimelineScreen() {
  const colorScheme = useColorScheme();
  const colors = Colors[colorScheme ?? 'light'] as typeof Colors.light;
  const categoryEmojiMap = useCategoryEmojiMap();
  const { setLoading } = useLoading();
  const pendingOpsRef = useRef(0);
  const beginLoad = useCallback(() => {
    pendingOpsRef.current += 1;
    setLoading(true);
  }, [setLoading]);
  const endLoad = useCallback(() => {
    pendingOpsRef.current = Math.max(0, pendingOpsRef.current - 1);
    if (pendingOpsRef.current === 0) {
      setLoading(false);
    }
  }, [setLoading]);
  const router = useRouter();
  const [monthStartDay, setMonthStartDay] = useState(1);
  
  // Navigation lock to prevent duplicate navigation
  const isNavigating = useRef(false);

  // Year/Month options for picker (홈 화면과 동일하게 ±10년)
  const yearOptions = useMemo(() => {
    const currentYear = new Date().getFullYear();
    return Array.from({ length: 21 }, (_, i) => {
      const year = currentYear - 10 + i;
      return {
        label: `${year}년`,
        value: year,
      };
    });
  }, []);

  const monthOptions = useMemo(() => {
    const months = [];
    for (let i = 1; i <= 12; i++) {
      months.push({ label: `${i}월`, value: i });
    }
    return months;
  }, []);
  
  // Params from home screen
  const params = useLocalSearchParams<{
    year?: string;
    month?: string;
    selectedDate?: string;
    tab?: string;
  }>();
  
  // 실제 현재 날짜 (개발자 모드 오버라이드와 분리)
  const realCurrentDate = {
    getFullYear: () => 2025,
    getMonth: () => 9, // 10월 (0부터 시작)
    getDate: () => 21
  };
  
  const [currentYear, setCurrentYear] = useState(params.year ? parseInt(params.year) : realCurrentDate.getFullYear());
  const [currentMonth, setCurrentMonth] = useState(params.month ? parseInt(params.month) : realCurrentDate.getMonth() + 1);
  
  const year = currentYear;
  const month = currentMonth;
  const initialYearParam = params.year ? parseInt(params.year, 10) : undefined;
  const initialMonthParam = params.month ? parseInt(params.month, 10) : undefined;

  const defaultTargetDate = useMemo(
    () => `${year}-${String(month).padStart(2, '0')}-01`,
    [year, month]
  );
  const targetDateFromSelection = useMemo(() => {
    const selectedDateParam = params.selectedDate;
    const hasValidSelectedDate =
      typeof selectedDateParam === 'string' &&
      /^\d{4}-\d{2}-\d{2}$/.test(selectedDateParam);

    // 홈에서 전달받은 최초 선택 날짜는 최초 진입 월에서만 유지하고,
    // 타임라인 내부에서 월을 바꾼 경우에는 현재 월 1일 기준으로 복귀 컨텍스트를 맞춘다.
    if (
      hasValidSelectedDate &&
      initialYearParam === year &&
      initialMonthParam === month
    ) {
      return selectedDateParam;
    }

    return defaultTargetDate;
  }, [defaultTargetDate, initialMonthParam, initialYearParam, month, params.selectedDate, year]);

  // 스와이프 뒤로가기를 포함한 모든 복귀 경로에서 홈 월 컨텍스트 유지
  useEffect(() => {
    const targetDate = targetDateFromSelection;
    setLatestPendingCalendarTarget({ year, month, targetDate });
    // 실시간 동기화: 타임라인 월 변경 즉시 홈의 월 컨텍스트도 갱신
    applyPendingCalendarTargetEvent.emit({ year, month, targetDate });
    void AsyncStorage.setItem(
      'pendingCalendarTarget',
      JSON.stringify({ year, month, targetDate }),
    ).catch(() => {
      // ignore
    });
  }, [year, month, targetDateFromSelection]);
  
  // Tab state
  const initialTab = params.tab === 'status' ? 'status' : 'timeline';
  const [activeTab, setActiveTab] = useState<'timeline' | 'status'>(initialTab);
  
  // Timeline data
  const [timelineData, setTimelineData] = useState<TimelineItem[]>([]);
  
  // Category expense data
  const [categoryExpenses, setCategoryExpenses] = useState<{
    category: string;
    count: number;
    amount: number;
    memo?: string;
  }[]>([]);
  
  // Filter state for category view
  const [categoryFilter, setCategoryFilter] = useState<'all' | 'recurring'>('all');
  
  // 페이드인 효과를 위한 state
  const [isContentReady, setIsContentReady] = useState(false);
  const contentOpacity = useRef(new Animated.Value(0)).current;
  const hasAnimatedRef = useRef(false);
  
  // Removed: Timeline data loading moved to useFocusEffect below

  // Calculate category expenses from timeline data
  useEffect(() => {
    
    const categoryMap = new Map<string, { count: number; amount: number; memo?: string }>();
    
    timelineData.forEach((item) => {
      if (item.type === 'expense') {
        // Filter by type if needed
        if (categoryFilter === 'recurring' && !item.isRecurring) return;
        if (categoryFilter === 'all' && item.isRecurring) return;
        
        const category = item.category || '기타';
        const amount = item.amount || 0;
        
        if (categoryMap.has(category)) {
          const existing = categoryMap.get(category)!;
          existing.count += 1;
          existing.amount += amount;
          if (item.memo && !existing.memo) {
            existing.memo = item.memo;
          }
        } else {
          categoryMap.set(category, {
            count: 1,
            amount: amount,
            memo: item.memo
          });
        }
      }
    });
    
    // Convert to array and sort by amount (descending)
    const expenses = Array.from(categoryMap.entries())
      .map(([category, data]) => ({
        category,
        count: data.count,
        amount: data.amount,
        memo: data.memo
      }))
      .sort((a, b) => b.amount - a.amount);

    setCategoryExpenses(expenses);
  }, [timelineData, categoryFilter, year, month, monthStartDay]);

  // Load challenge data - REMOVED (useFocusEffect에서 처리)

  // 데이터 새로고침 함수
  const refreshData = useCallback(async () => {
        beginLoad();
        try {
          if (!hasAnimatedRef.current) {
            setIsContentReady(false);
          }
          
          // Load month start day
          const monthStart = await loadMonthStartDay();
          setMonthStartDay(monthStart);
          
          // 타임라인 데이터 새로고침
          const storedData = await AsyncStorage.getItem('calendarData');
          if (storedData) {
            // recurringType이 null인 경우 undefined로 변환 (JSON.parse reviver)
            const parsed = JSON.parse(storedData, (key, value) => {
              if (key === 'recurringType' && value === null) {
                return undefined;
              }
              return value;
            });
            const calendarData = parsed;
            const items: TimelineItem[] = [];
            let includedDates: string[] = [];
            let excludedDates: string[] = [];
            
            Object.entries(calendarData).forEach(([dateString, data]: [string, any]) => {
              // 날짜 문자열을 로컬 타임존으로 파싱
              const [yearStr, monthStr, dayStr] = dateString.split('-');
              const date = new Date(parseInt(yearStr), parseInt(monthStr) - 1, parseInt(dayStr));
              
              // Use custom month filtering
              const isIncluded = isDateInCustomMonth(date, year, month, monthStart);
              
              if (isIncluded) {
                includedDates.push(dateString);
                if (data.records && Array.isArray(data.records)) {
                  data.records.forEach((record: any, recordIndex: number) => {
                    // isDeleted가 true인 기록 제외 (환불된 기록은 표시)
                    if (record.isDeleted) return;
                    
                    items.push({
                      id: record.id,
                      date: dateString,
                      type: record.type,
                      category: record.category || '기타',
                      memo: record.memo,
                      amount: record.amount || 0,
                      timestamp: record.timestamp,
                      paymentMethod: record.type === 'expense' ? (record.paymentMethod ?? 'credit') : undefined,
                      isRecurring: record.isRecurring,
                      weekendOption: record.weekendOption,
                      recurringType: record.recurringType,
                      isPrepaid: record.isPrepaid,
                      prepaidDate: record.prepaidDate, // 선결제 처리 날짜
                      recurringId: record.recurringId,
                      installmentId: record.installmentId,
                      installmentOriginDate: record.installmentOriginDate,
                      originalDate: record.originalDate,
                      isAutoGenerated: record.isAutoGenerated,
                      actualRecordIndex: recordIndex,
                      isInstallment: record.isInstallment,
                      originalInstallment: record.originalInstallment,
                      totalMonths: record.totalMonths,
                      isRefunded: record.isRefunded, // 환불 여부
                      isSettled: record.isSettled,
                      settledAt: record.settledAt,
                      originalAmountBeforeSettlement: record.originalAmountBeforeSettlement,
                    });
                  });
                }
              } else {
                // 샘플로 제외된 날짜 3개만 저장
                if (excludedDates.length < 3) {
                  excludedDates.push(dateString);
                }
              }
            });

            // Sort by date (newest first), then by timestamp within same date
            items.sort((a, b) => {
              const dateCompare = new Date(b.date).getTime() - new Date(a.date).getTime();
              if (dateCompare !== 0) return dateCompare;
              return (b.timestamp || 0) - (a.timestamp || 0);
            });
            
            setTimelineData(items);
          }

          // 데이터 로드 완료 후 페이드인 준비
          setIsContentReady(true);
          hasAnimatedRef.current = true;
        } catch {
          setIsContentReady(true); // 에러 발생 시에도 페이드인 처리
          hasAnimatedRef.current = true;
        } finally {
          endLoad();
        }
  }, [year, month, beginLoad, endLoad]);

  // 화면 포커스 시마다 새로고침 (삭제/수정 후 복귀 시 반영)
  useFocusEffect(
    useCallback(() => {
      refreshData();
    }, [refreshData])
  );

  // 데이터 변경 시에만 새로고침 (홈과 동일한 정책)
  const { dataVersion } = useAppData();
  useEffect(() => {
    refreshData();
  }, [dataVersion, year, month, refreshData]);

  // 전역 이벤트 구독은 컨텍스트에서 처리하므로 제거 (중복 새로고침 방지)

  // 페이드인 애니메이션 처리
  useEffect(() => {
    if (isContentReady) {
      contentOpacity.setValue(0);
      Animated.timing(contentOpacity, {
        toValue: 1,
        duration: 200,
        useNativeDriver: true,
      }).start();
    } else {
      contentOpacity.setValue(0);
    }
  }, [isContentReady, contentOpacity]);
  
  // Calculate monthly totals
  const monthlyTotals = useMemo(() => {
    let income = 0;
    let expense = 0;
    
    timelineData.forEach((item) => {
      if (item.type === 'income') {
        income += item.amount;
      } else {
        expense += item.amount;
      }
    });
    
    return { income, expense };
  }, [timelineData]);

  
  // Group timeline items by date
  const groupedTimeline = useMemo(() => {
    const groups: Record<string, TimelineItem[]> = {};
    
    timelineData.forEach((item) => {
      if (!groups[item.date]) {
        groups[item.date] = [];
      }
      groups[item.date].push(item);
    });
    
    return groups;
  }, [timelineData]);
  
  // Format date for display
  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}.${month}.${day}`;
  };
  
  const handleBackPress = useCallback(() => {
    void (async () => {
      const targetDate = targetDateFromSelection;
      setLatestPendingCalendarTarget({ year, month, targetDate });
      // 홈 화면이 이미 마운트되어 있으면 즉시 상태를 맞춰 점프를 제거
      applyPendingCalendarTargetEvent.emit({ year, month, targetDate });
      try {
        await AsyncStorage.setItem(
          'pendingCalendarTarget',
          JSON.stringify({ year, month, targetDate }),
        );
      } catch {
        // ignore
      }

      if (router.canGoBack()) {
        router.back();
        return;
      }
      // 스택이 없는 진입에서도 홈 월 컨텍스트를 유지하도록 파라미터 전달
      router.replace({
        pathname: '/(tabs)/home',
        params: {
          targetYear: year.toString(),
          targetMonth: month.toString(),
          targetDate,
        },
      });
    })();
  }, [month, router, targetDateFromSelection, year]);
  
  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]} edges={['top', 'bottom']}>
      {/* Top Navigation */}
      <Animated.View style={{ opacity: isContentReady ? contentOpacity : 0 }}>
        <TopNavigation
          type="sub"
          title=""
          showDay
          dateText={`${year}년 ${String(month).padStart(2, '0')}월`}
          showLeftIcon
          onLeftIconPress={handleBackPress}
          showDropdownArrow
          yearOptions={yearOptions}
          selectedYear={year}
          onYearChange={(newYear) => {
            const minYear = yearOptions[0]?.value ?? newYear;
            const maxYear = yearOptions[yearOptions.length - 1]?.value ?? newYear;
            const clampedYear = Math.min(maxYear, Math.max(minYear, newYear));
            setCurrentYear(clampedYear);
          }}
          monthOptions={monthOptions}
          selectedMonth={month}
          onMonthChange={(newMonth) => {
            // 홈 화면과 동일하게 단순화 - 년도/월을 독립적으로 변경
            setCurrentMonth(newMonth);
          }}
        />
      </Animated.View>
      
      {/* Tab Menu */}
      <Animated.View style={{ opacity: isContentReady ? contentOpacity : 0 }}>
        <Tab
          options={[
            { label: '타임라인', value: 'timeline' },
            { label: '소비 현황', value: 'status' },
          ]}
          value={activeTab}
          onValueChange={setActiveTab}
        />
        
        {/* Month Summary - Only show for timeline tab */}
        {activeTab === 'timeline' && (
          <View style={[styles.summaryContainer, { backgroundColor: colors.background }]}>
            <Text style={[styles.summaryMonth, { color: colors.staticBlack }]}>
              {(() => {
                // 월 시작일 기준으로 실제 범위 계산
                const { startDate, endDate } = getCustomMonthRange(year, month, monthStartDay);
                
                const startMonth = String(startDate.getMonth() + 1).padStart(2, '0');
                const startDay = String(startDate.getDate()).padStart(2, '0');
                const endMonth = String(endDate.getMonth() + 1).padStart(2, '0');
                const endDay = String(endDate.getDate()).padStart(2, '0');
                
                return `${startMonth}.${startDay} - ${endMonth}.${endDay}`;
              })()}
            </Text>
            
            <View style={styles.summaryAmounts}>
              <View style={styles.summaryIncomeContainer}>
                <Text 
                  style={[styles.summaryIncome, { color: colors.text }]}
                  adjustsFontSizeToFit
                  numberOfLines={1}
                  minimumFontScale={0.7}
                >
                  + {monthlyTotals.income.toLocaleString()}원
                </Text>
              </View>
              
              <View style={[styles.summaryDivider, { backgroundColor: colors.border }]} />
              
              <View style={styles.summaryExpenseContainer}>
                <Text 
                  style={[styles.summaryExpense, { color: colors.text }]}
                  adjustsFontSizeToFit
                  numberOfLines={1}
                  minimumFontScale={0.7}
                >
                  - {monthlyTotals.expense.toLocaleString()}원
                </Text>
              </View>
            </View>
          </View>
        )}
        
        {/* Divider - Only show for timeline tab */}
        {activeTab === 'timeline' && (
          <View style={styles.headerDivider} />
        )}
      </Animated.View>
      
      {/* Content based on active tab */}
      <Animated.View style={{ opacity: isContentReady ? contentOpacity : 0, flex: 1 }}>
      {activeTab === 'timeline' ? (
        /* Timeline Content */
        <ScrollView 
          style={styles.scrollContainer}
          contentContainerStyle={styles.scrollContent}
        >
        {Object.keys(groupedTimeline).length === 0 ? (
          <View style={styles.emptyContainer}>
            <Text style={[styles.emptyText, { color: colors.textAssistive }]}>
              이 달의 기록이 없습니다.
            </Text>
          </View>
        ) : (
          Object.entries(groupedTimeline).map(([date, items], groupIndex) => {
            const totalGroups = Object.keys(groupedTimeline).length;
            const isLastGroup = groupIndex === totalGroups - 1;
            
            return (
              <View key={date} style={styles.dateGroup}>
                {items.map((item, itemIndex) => {
                  const isFirstInGroup = itemIndex === 0;
                  const isLastInGroup = itemIndex === items.length - 1;
                  
                  return (
                    <View key={`${date}-${itemIndex}`}>
                      <Pressable 
                        style={styles.timelineItem}
                        onPress={async () => {
                          
                          if (item.type === 'expense') {
                            
                            // 실제 데이터에서 정확한 recordIndex 찾기
                            let correctRecordIndex = item.actualRecordIndex || 0;
                            
                            try {
                              const storedData = await AsyncStorage.getItem('calendarData');
                              if (storedData) {
                                // recurringType이 null인 경우 undefined로 변환 (JSON.parse reviver)
                                const calendarData = JSON.parse(storedData, (key, value) => {
                                  if (key === 'recurringType' && value === null) {
                                    return undefined;
                                  }
                                  return value;
                                });
                                const dateRecords = calendarData[date]?.records || [];

                                // timestamp와 category, amount로 정확한 인덱스 찾기
                                const foundIndex = dateRecords.findIndex((record: any) => 
                                  record.timestamp === item.timestamp &&
                                  record.category === item.category &&
                                  record.amount === item.amount
                                );

                                if (foundIndex !== -1) {
                                  correctRecordIndex = foundIndex;

                                } else {

                                  // 대안: category와 amount만으로 찾기
                                  const fallbackIndex = dateRecords.findIndex((record: any) => 
                                    record.category === item.category &&
                                    record.amount === item.amount
                                  );
                                  
                                  if (fallbackIndex !== -1) {
                                    correctRecordIndex = fallbackIndex;

                                  }
                                }
                              }
                            } catch {

                            }

                            // 소비 기록인 경우 수정화면으로 이동
                            router.push({
                              pathname: '/expense-edit',
                              params: {
                                recordData: JSON.stringify(item),
                                dateKey: date,
                                recordIndex: correctRecordIndex.toString(),
                                calendarYear: year.toString(),
                                calendarMonth: month.toString(),
                              },
                            });

                          } else if (item.type === 'income') {

                            // 실제 데이터에서 정확한 recordIndex 찾기
                            let correctRecordIndex = item.actualRecordIndex || 0;
                            
                            try {
                              const storedData = await AsyncStorage.getItem('calendarData');
                              if (storedData) {
                                // recurringType이 null인 경우 undefined로 변환 (JSON.parse reviver)
                                const calendarData = JSON.parse(storedData, (key, value) => {
                                  if (key === 'recurringType' && value === null) {
                                    return undefined;
                                  }
                                  return value;
                                });
                                const dateRecords = calendarData[date]?.records || [];

                                // timestamp와 category, amount로 정확한 인덱스 찾기
                                const foundIndex = dateRecords.findIndex((record: any) => 
                                  record.timestamp === item.timestamp &&
                                  record.category === item.category &&
                                  record.amount === item.amount
                                );
                                
                                if (foundIndex !== -1) {
                                  correctRecordIndex = foundIndex;

                                } else {

                                  // 대안: category와 amount만으로 찾기
                                  const fallbackIndex = dateRecords.findIndex((record: any) => 
                                    record.category === item.category &&
                                    record.amount === item.amount
                                  );
                                  
                                  if (fallbackIndex !== -1) {
                                    correctRecordIndex = fallbackIndex;

                                  }
                                }
                              }
                            } catch {

                            }

                            // 수입 기록인 경우 수정화면으로 이동
                            router.push({
                              pathname: '/income-edit',
                              params: {
                                recordData: JSON.stringify(item),
                                dateKey: date,
                                recordIndex: correctRecordIndex.toString(),
                                calendarYear: year.toString(),
                                calendarMonth: month.toString(),
                              },
                            });

                          }
                        }}
                      >
                        {/* Date Column */}
                        <View style={styles.dateColumn}>
                          {isFirstInGroup && (
                            <Text style={[styles.dateText, { color: colors.textAssistive }]}>
                              {formatDate(date)}
                            </Text>
                          )}
                        </View>
                        
                        {/* Content: Category/Amount + Memo */}
                        <View style={styles.itemContent}>
                          {/* Category and Amount */}
                          <View style={styles.itemRow1}>
                            <View style={styles.categoryContainer}>
                              <Text 
                                style={[styles.categoryText, { color: colors.text }]}
                              >
                                {(() => {
                                  const label = item.category || '수입';
                                  const emoji = categoryEmojiMap[label];
                                  if (emoji) {
                                    return `${emoji} ${label}`;
                                  }
                                  if (item.type === 'income') {
                                    if (label === '수입' || label === '입금' || !label) {
                                      return '💰 수입';
                                    }
                                    return label;
                                  }
                                  return label;
                                })()}
                              </Text>
                            </View>
                            <View style={styles.amountContainer}>
                              <Text 
                                style={[styles.amountText, { color: colors.text }]}
                                adjustsFontSizeToFit
                                numberOfLines={1}
                                minimumFontScale={0.7}
                              >
                                {item.type === 'expense'
                                  ? (
                                    // 결산/할부 환불 기록은 부호 없이 표기
                                    item.isSettled || (item.isInstallment && item.isRefunded)
                                      ? `${item.amount.toLocaleString()}원`
                                      : `- ${item.amount.toLocaleString()}원`
                                    )
                                  : `+ ${item.amount.toLocaleString()}원`
                                }
                              </Text>
                            </View>
                          </View>
                          
                          {/* Memo */}
                          <View style={styles.itemRow2}>
                            <View style={styles.memoContainer}>
                              <Text
                                style={[styles.memoText, { color: colors.textAssistive }]}
                              >
                                {item.memo ? item.memo.replace(/\n/g, ' ') : ' '}
                              </Text>
                              {/* 태그 표시 */}
                              {item.isInstallment && item.isSettled && (
                                <Tag
                                  label="할부·결산"
                                  status="negative"
                                />
                              )}
                              {item.isInstallment && item.isPrepaid && !item.isSettled && (
                                <Tag 
                                  label="할부·선결제" 
                                  status="positive" 
                                />
                              )}
                              {item.isInstallment && !item.isPrepaid && !item.isSettled && (
                                <Tag 
                                  label={item.isRefunded ? "할부·환불" : "할부"} 
                                  status="negative" 
                                />
                              )}
                              {!item.isInstallment && item.isSettled && (
                                <Tag
                                  label={item.isRecurring ? "정기·결산" : "일반·결산"}
                                  status="normal"
                                />
                              )}
                              {!item.isInstallment && item.isPrepaid && !item.isSettled && (
                                <Tag label="선납" status="positive" />
                              )}
                              {!item.isInstallment && item.isRefunded && !item.isSettled && (
                                <Tag
                                  label={item.isRecurring ? "정기·환불" : "일반·환불"}
                                  status="normal"
                                />
                              )}
                              {!item.isInstallment && item.isRecurring && !item.isPrepaid && !item.isRefunded && !item.isSettled && (
                                <Tag label="정기" status="normal" />
                              )}
                            </View>
                          </View>
                        </View>
                      </Pressable>
                      
                      {/* Item Divider - 자식 리스트 하단 */}
                      {!isLastInGroup && (
                        <View style={[styles.itemDivider, { backgroundColor: colors.border }]} />
                      )}
                    </View>
                  );
                })}
                
                {/* Date Group Divider */}
                {!isLastGroup && (
                  <View style={[styles.dateGroupDivider, { backgroundColor: colors.border }]} />
                )}
              </View>
            );
          })
        )}
        </ScrollView>
      ) : activeTab === 'status' ? (
        /* Category Expense Status Content */
        <ScrollView 
          style={[styles.scrollContainer, { backgroundColor: colors.fill }]}
          contentContainerStyle={styles.scrollContent}
        >
          {/* Filter Chips */}
          <View style={styles.filterContainer}>
            <Chip
              label="이번달 지출 순위"
              active={categoryFilter === 'all'}
              onPress={() => setCategoryFilter('all')}
            />
            <Chip
              label="정기 지출"
              active={categoryFilter === 'recurring'}
              onPress={() => setCategoryFilter('recurring')}
            />
          </View>
          
          {/* Category List */}
          {categoryExpenses.length === 0 ? (
            <View style={styles.emptyContainer}>
              <Text style={[styles.emptyText, { color: colors.textAssistive }]}>
                {categoryFilter === 'all' ? '이번달 지출 내역이 없습니다.' : '정기 지출 내역이 없습니다.'}
              </Text>
              {categoryFilter === 'all' && (
                <Text style={[styles.emptyText, { color: colors.textAssistive }]}>
                  0원
                </Text>
              )}
            </View>
          ) : (
            <View style={styles.categoryList}>
              {categoryExpenses.map((item, index) => (
                <View key={item.category}>
                  <Pressable
                    style={[styles.categoryItemStatus, { backgroundColor: colors.staticWhite }]}
                    onPress={() => {
                      router.push({
                        pathname: '/expense-category-detail',
                        params: {
                          category: item.category,
                          year: year.toString(),
                          month: month.toString(),
                        },
                      });
                    }}
                  >
                    <View style={styles.categorySection}>
                      <Text style={[styles.categoryName, { color: colors.text }]}>
                        {categoryEmojiMap[item.category] || '📝'} {item.category}
                      </Text>
                      <Text style={[styles.categoryStatsText, { color: colors.text }]}>
                        {categoryFilter === 'recurring' 
                          ? `${item.amount.toLocaleString()}원`
                          : `${item.count}건 · ${item.amount.toLocaleString()}원`
                        }
                      </Text>
                    </View>
                  </Pressable>
                </View>
              ))}
            </View>
          )}
        </ScrollView>
      ) : (
        /* Challenge Status Content */
        <ScrollView 
          style={[styles.scrollContainer, { backgroundColor: colors.fill }]}
          contentContainerStyle={styles.scrollContent}
        >
          {challenges.length === 0 ? (
            <View style={styles.emptyContainer}>
              <Text style={[styles.emptyText, { color: colors.textAssistive }]}>
                생성된 챌린지가 없습니다.
              </Text>
            </View>
          ) : (
            <View style={styles.challengeList}>
              {challenges.map((challenge) => {
                const categoryEmoji = categoryEmojiMap[challenge.category];
                
                // 안전한 targetAmount 처리
                let targetAmount = 0;
                if (challenge.targetAmount) {
                  if (typeof challenge.targetAmount === 'string') {
                    const cleanAmount = (challenge.targetAmount as string).replace(/,/g, '');
                    targetAmount = parseInt(cleanAmount) || 0;
                  } else if (typeof challenge.targetAmount === 'number') {
                    targetAmount = challenge.targetAmount;
                  }
                }
                
                // 미리 계산된 챌린지 소비금액 사용
                const currentAmount = challengeAmounts[challenge.id] || 0;
                const progress = targetAmount > 0 ? (currentAmount / targetAmount) * 100 : 0;
                const isOverBudget = currentAmount > targetAmount;
                
                // 챌린지 상태 계산 (피그마 디자인에 맞게)
                const getChallengeStatus = () => {
                  const today = new Date();
                  today.setHours(0, 0, 0, 0); // 시간 제거
                  
                  const startDate = new Date(challenge.startDate.replace(/\./g, '-'));
                  startDate.setHours(0, 0, 0, 0);
                  
                  const endDate = new Date(challenge.endDate.replace(/\./g, '-'));
                  endDate.setHours(0, 0, 0, 0);
                  
                  
                  
                  // 챌린지 시작일 판단 (단순히 현재 날짜와 비교)
                  const isChallengeStarted = () => {
                    
                    
                    // 챌린지 시작일이 현재 날짜 이전 또는 같은 날인지 확인
                    return startDate <= today;
                  };
                  
                  // 시작일이 미래인 경우: "진행 전"
                  if (!isChallengeStarted()) {

                    return { 
                      text: '진행 전', 
                      color: '#222222', 
                      bgColor: 'transparent', 
                      showProgressComplete: false,
                      isBeforeStart: true
                    };
                  }
                  
                  // 챌린지가 진행 중인 경우: 남은 기간 표시
                  const daysLeft = Math.ceil((endDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));

                  if (daysLeft < 0) {
                    return { 
                      text: isOverBudget ? 'Failed' : 'Success', 
                      color: isOverBudget ? '#ef5252' : '#07b63b', 
                      bgColor: isOverBudget ? '#ef5252' : '#07b63b',
                      showProgressComplete: true,
                      isBeforeStart: false
                    };
                  } else if (daysLeft === 0) {
                    return { text: 'D-0', color: '#222222', bgColor: 'transparent', showProgressComplete: false, isBeforeStart: false };
                  } else {
                    return { text: `D-${daysLeft}`, color: '#222222', bgColor: 'transparent', showProgressComplete: false, isBeforeStart: false };
                  }
                };
                
                const status = getChallengeStatus();
                
                return (
                    <Pressable 
                    key={challenge.id} 
                    style={[styles.challengeCard, { backgroundColor: colors.staticWhite }]}
                    onPress={() => {
                      // 중복 네비게이션 방지
                      if (isNavigating.current) {

                        return;
                      }
                      
                      isNavigating.current = true;

                      router.push({
                        pathname: '/challenge-detail',
                        params: {
                          challengeId: challenge.id
                        }
                      });
                      
                      // 500ms 후 네비게이션 잠금 해제
                      setTimeout(() => {
                        isNavigating.current = false;
                      }, 500);
                    }}
                  >
                      {/* Challenge Header - 피그마 디자인에 맞게 */}
                      <View style={styles.challengeHeader}>
                        <View style={styles.challengeCategory}>
                          <Text style={[styles.challengeCategoryName, { color: colors.text }]}>
                            {categoryEmoji || '📝'} {challenge.category}
                          </Text>
                        </View>
                        <View style={styles.challengeStatusContainer}>
                          {status.showProgressComplete && (
                            <View style={[styles.challengeStatus, { gap: 0 }]}>
                              {status.bgColor !== 'transparent' ? (
                                <View style={[styles.statusBadge, { backgroundColor: status.bgColor }]}>
                                  <Text style={[styles.statusText, { color: '#ffffff' }]}>
                                    {status.text}
                                  </Text>
                                </View>
                              ) : (
                                <Text style={[styles.statusLabel, { color: status.color }]}>
                                  {status.text}
                                </Text>
                              )}
                            </View>
                          )}
                          <Text style={[styles.statusLabel, { color: colors.text }]}>
                            {status.showProgressComplete ? '종료' : status.text}
                          </Text>
                        </View>
                      </View>
                    
                    {/* Progress Bar - 피그마 디자인에 맞게 */}
                    <View style={[styles.progressContainer, { backgroundColor: '#E3E3E3' }]}>
                      <View 
                        style={[
                          styles.progressBar, 
                          { 
                            width: status.isBeforeStart ? '5%' : `${Math.max(progress, 1)}%`, // 진행 전: 5%, 진행 중: 최소 1% 표시
                            backgroundColor: status.isBeforeStart ? '#9e9e9e' : (isOverBudget ? '#F66262' : '#1AC673')
                          }
                        ]} 
                      />
                    </View>
                    
                    {/* Amount Info - 피그마 디자인에 맞게 좌우 배치 */}
                    <View style={styles.challengeAmounts}>
                      <View style={styles.amountLeft}>
                        <Text style={[styles.amountLabel, { color: '#9e9e9e' }]}>
                          현재 소비금액
                        </Text>
                        <Text style={[styles.amountValue, { color: '#424242' }]}>
                          {status.isBeforeStart ? '0원' : `${currentAmount.toLocaleString()}원`}
                        </Text>
                      </View>
                      <View style={styles.amountRight}>
                        <Text style={[styles.amountLabel, { color: '#9e9e9e' }]}>
                          목표 소비금액
                        </Text>
                        <Text style={[styles.amountValue, { color: '#424242' }]}>
                          {targetAmount.toLocaleString()}원
                        </Text>
                      </View>
                    </View>
                  </Pressable>
                );
              })}
            </View>
          )}
        </ScrollView>
      )}
      </Animated.View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  summaryContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  summaryMonth: {
    ...Typography.body1.l.bold,
  },
  summaryAmounts: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    justifyContent: 'flex-end',
  },
  summaryIncomeContainer: {
    flexShrink: 1,
    alignItems: 'center',
  },
  summaryIncome: {
    ...Typography.body1.l.bold,
  },
  summaryDivider: {
    width: 1,
    height: 8,
  },
  summaryExpenseContainer: {
    flexShrink: 1,
    alignItems: 'center',
  },
  summaryExpense: {
    ...Typography.body1.l.bold,
  },
  headerDivider: {
    height: 8,
    width: '100%',
    backgroundColor: 'rgba(144, 146, 158, 0.1)',
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 0, // 내용물 크기만큼만, 늘어나지 않음
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 80,
  },
  emptyText: {
    ...Typography.body1.l.regular,
  },
  dateGroup: {
    // No padding - handled by individual items
  },
  timelineItem: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16, // 상하 패딩 16px
    // height 제거 - 내용에 따라 자동 조정
  },
  timelineItemWithDivider: {
    borderBottomWidth: 1,
    borderBottomColor: 'transparent', // 기본값, 동적으로 설정됨
    marginHorizontal: 16, // 좌우 여백 추가
  },
  dateColumn: {
    width: 94,
  },
  dateText: {
    ...Typography.body1.l.medium,
  },
  itemContent: {
    flex: 1,
    flexDirection: 'column',
    gap: 4,
  },
  itemRow1: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  itemRow2: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  categoryContainer: {
    flex: 6,
  },
  categoryText: {
    ...Typography.body1.l.bold,
    lineHeight: 24,
  },
  amountContainer: {
    flex: 4,
    alignItems: 'flex-end',
  },
  amountText: {
    ...Typography.body1.l.bold,
    textAlign: 'right',
  },
  memoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  memoText: {
    ...Typography.body2.r.regular,
    lineHeight: 21,
    flex: 1,
  },
  itemDivider: {
    height: 1,
    marginLeft: 110, // 16 + 94 = padding + date column width
    marginTop: 0,    // 상단 여백 0
    marginBottom: 0, // 하단 여백 0
  },
  dateGroupDivider: {
    height: 1,
    width: '100%',        // 가로값 100%
    marginTop: 0,         // 상단 여백 제거
    marginBottom: 0,      // 하단 여백 제거
    marginHorizontal: 16, // 양옆 여백 유지
  },
  // Category expense styles
  filterContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 8,
  },
  categoryList: {
    paddingBottom: 20,
  },
  categoryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 16,
    marginBottom: 8,
    marginHorizontal: 16,
  },
  categorySection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  categoryName: {
    fontSize: 16,
    fontFamily: 'Pretendard',
    fontWeight: '700',
    lineHeight: 24,
    flex: 1,
  },
  categoryStatsText: {
    fontSize: 16,
    fontFamily: 'Pretendard',
    fontWeight: '700',
    lineHeight: 24,
  },
  categorySeparator: {
    height: 1,
    marginHorizontal: 16,
  },
  // 소비현황 탭 전용 스타일
  categoryItemStatus: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 16,
    marginBottom: 8,
    marginHorizontal: 16,
  },
  // 챌린지 현황 탭 전용 스타일 - 피그마 디자인에 맞게
  challengeList: {
    padding: 16,
  },
  challengeCard: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  challengeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  challengeCategory: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  challengeStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  challengeCategoryName: {
    ...Typography.body1.l.bold,
    fontSize: 16,
    lineHeight: 24,
  },
  challengeStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginLeft: 8,
  },
  statusBadge: {
    borderRadius: 4,
    paddingHorizontal: 4,
  },
  statusText: {
    ...Typography.tiny.r.bold,
    fontSize: 12,
    lineHeight: 18,
  },
  statusLabel: {
    ...Typography.body1.l.bold,
    fontSize: 16,
    lineHeight: 24,
  },
  progressContainer: {
    height: 10,
    borderRadius: 8,
    marginBottom: 16,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    borderRadius: 8,
  },
  challengeAmounts: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  amountLeft: {
    alignItems: 'flex-start',
  },
  amountRight: {
    alignItems: 'flex-end',
  },
  amountLabel: {
    ...Typography.tiny.r.regular,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 2,
  },
  amountValue: {
    ...Typography.body1.l.bold,
    fontSize: 16,
    lineHeight: 24,
  },
});

