//
//  awalletStageWidgetBundle.swift
//  awalletStageWidget
//
//  Created by Ssong on 1/29/26.
//

import WidgetKit
import SwiftUI

// NOTE:
// This bundle was generated by Xcode's template. We now use `MonthlyExpenseWidget`
// (defined in the shared widget source) as the single entry point via its own
// `@main` declaration, so this bundle is no longer marked as `@main`.
// It remains only as a thin wrapper around `MonthlyExpenseWidget` if needed.
struct awalletStageWidgetBundle: WidgetBundle {
    var body: some Widget {
        MonthlyExpenseWidget()
    }
}
