//
//  awalletWidgetBundle.swift
//  awalletWidget
//
//  Created by Ssong on 1/29/26.
//

import WidgetKit
import SwiftUI

// NOTE:
// This bundle was generated by Xcode's template. We now use `MonthlyExpenseWidget`
// (defined in `MonthlyExpenseWidget.swift`) as the single entry point for this
// module via its own `@main` declaration, so this bundle no longer needs to be
// marked as `@main`. It is kept only for reference and is not used at runtime.
struct awalletWidgetBundle: WidgetBundle {
    var body: some Widget {
        MonthlyExpenseWidget()
    }
}
