import AsyncStorage from '@react-native-async-storage/async-storage';
import { registerReviewPromptLifetimeCreations } from '@/utils/app-store-review-lifetime';
import { scheduleMaybePromptWriteReview } from '@/utils/app-store-review-scheduler';
import { calculateRecurringIterations } from '@/utils/expense-calculations';
import {
  logExpenseCreate,
  logExpenseDelete,
  type ExpenseAdjustmentKind,
  type ExpenseAdjustmentState,
  type ExpenseCreationCompletionPayload,
  type ExpenseCreationVariant,
  type ExpenseLifecycleAnalyticsPayload,
  type ExpensePeriodUnit,
  type ExpenseRefundScopeAnalytics,
  type ExpenseRepeatKind,
  type ExpenseSettlementKind,
  type ExpenseSimpleCreationValue,
  type ExpenseWeekendOptionAnalytics,
} from '@/utils/analytics';
import { generateRecordId } from './id-generator';

export type PaymentMethod = 'credit' | 'debit' | 'cash';

export interface ExpenseRecord {
  id?: string; // UUID v4 (생성 시 자동 할당)
  type: 'expense';
  amount: number;
  category: string;
  memo?: string;
  date: string; // YYYY.MM.DD 형식
  timestamp: number;
  paymentMethod?: PaymentMethod;
  isRecurring?: boolean;
  weekendOption?: 'friday' | 'monday' | 'weekend';
  recurringId?: string;
  installmentId?: string;
  isAutoGenerated?: boolean;
  isInstallment?: boolean;
  totalMonths?: number; // 정기 기록 개월 수
  installmentMonths?: number; // 할부 기록 개월 수
  originalInstallment?: boolean;
  recurringType?: string; // 정기 기록의 반복 타입 (매일, 매주, 2주, 3주, 4주, 매월, 2개월 마다, 4개월 마다, 6개월 마다, 주중, 주말)
  isPrepaid?: boolean;
  prepaidDate?: string; // YYYY.MM.DD 형식
  isRefunded?: boolean;
  /** 환불 처리 시각(ISO). 백업·캘린더 행과 동기화 */
  refundedAt?: string;
  isSettled?: boolean;
  settledAt?: string;
  originalAmountBeforeSettlement?: number;
  installmentOriginDate?: string; // 할부 기록 원본 예정일 (선결제 시 사용)
  isDeleted?: boolean;
  deletedAt?: string | null;
  originalAmount?: number; // 원본 금액
  originalAmountBeforeRefund?: number; // 환불 직전 금액
  originalCategory?: string; // 원본 카테고리
  originalDate?: string; // 원본 날짜 (YYYY.MM.DD 형식) - 일반 기록: 처음 생성일, 선결제 기록: 원래 예정일
  /** 최초 생성 시각. 로컬 `YYYY-MM-DD HH:mm:ss` (없으면 로드 시 timestamp으로 백필) */
  createdAt?: string;
  /** 마지막 수정 시각. 로컬 `YYYY-MM-DD HH:mm:ss` (없으면 createdAt과 동일하게 백필) */
  updatedAt?: string;
  /**
   * 기록 생성 경로. `'simple'`은 간편입력 경로로 생성됐음을 의미.
   * 미지정(레거시/일반 생성 화면)은 non-simple로 간주.
   */
  createdVia?: 'simple' | 'screen';
}

const EXPENSE_STORAGE_KEY = 'expenseData';
const DATE_TOKEN_REGEX = /\./g;

function coerceTimestamp(record: ExpenseRecord): number {
  const raw = record.timestamp;
  if (typeof raw === 'number' && !Number.isNaN(raw)) {
    return raw;
  }
  const n = Number(raw);
  return Number.isFinite(n) ? n : Date.now();
}

/** 로컬 날짜+시간 문자열 (AsyncStorage 저장용) */
function formatLocalDateTime(ms: number): string {
  const d = new Date(ms);
  const y = d.getFullYear();
  const mo = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  const h = String(d.getHours()).padStart(2, '0');
  const min = String(d.getMinutes()).padStart(2, '0');
  const s = String(d.getSeconds()).padStart(2, '0');
  return `${y}-${mo}-${day} ${h}:${min}:${s}`;
}

function parseStoredDateTimeToMs(value: string): number | null {
  const t = Date.parse(value);
  return Number.isNaN(t) ? null : t;
}

function normalizeExpense(record: ExpenseRecord): ExpenseRecord {
  const timestamp = coerceTimestamp(record);
  const fallbackDt = formatLocalDateTime(timestamp);

  let createdAt: string;
  if (typeof record.createdAt === 'string' && record.createdAt.length > 0) {
    const ms = parseStoredDateTimeToMs(record.createdAt);
    createdAt = ms !== null ? formatLocalDateTime(ms) : fallbackDt;
  } else {
    createdAt = fallbackDt;
  }

  let updatedAt: string;
  if (typeof record.updatedAt === 'string' && record.updatedAt.length > 0) {
    const ms = parseStoredDateTimeToMs(record.updatedAt);
    updatedAt = ms !== null ? formatLocalDateTime(ms) : createdAt;
  } else {
    updatedAt = createdAt;
  }

  const normalized: ExpenseRecord = {
    ...record,
    id: record.id ?? generateRecordId(),
    type: 'expense',
    timestamp,
    createdAt,
    updatedAt,
    isDeleted: record.isDeleted ?? false,
    deletedAt: record.deletedAt ?? null,
    paymentMethod: record.paymentMethod ?? 'credit',
  };

  return normalized;
}

function sortByTimestampDescending(records: ExpenseRecord[]): ExpenseRecord[] {
  return [...records].sort((a, b) => b.timestamp - a.timestamp);
}

function sortByTimestampAscending(records: ExpenseRecord[]): ExpenseRecord[] {
  return [...records].sort((a, b) => a.timestamp - b.timestamp);
}

function isWithinDateRange(date: string, startDate: string, endDate: string): boolean {
  const normalizedDate = date.replace(DATE_TOKEN_REGEX, '');
  const normalizedStart = startDate.replace(DATE_TOKEN_REGEX, '');
  const normalizedEnd = endDate.replace(DATE_TOKEN_REGEX, '');
  return normalizedDate >= normalizedStart && normalizedDate <= normalizedEnd;
}

async function loadLocalExpenses(): Promise<ExpenseRecord[]> {
  try {
    const stored = await AsyncStorage.getItem(EXPENSE_STORAGE_KEY);
    if (!stored) {
      return [];
    }

    // recurringType이 null인 경우 undefined로 변환 (JSON.parse reviver)
    const parsed = JSON.parse(stored, (key, value) => {
      if (key === 'recurringType' && value === null) {
        return undefined;
      }
      return value;
    });
    if (!Array.isArray(parsed)) {
      return [];
    }

    return sortByTimestampDescending(
      parsed.map((item) =>
        normalizeExpense({
          ...item,
          timestamp: typeof item.timestamp === 'number' ? item.timestamp : Number(item.timestamp),
        }),
      ),
    );
  } catch (error) {
    console.error('[expenses] Failed to load local expenses:', error);
    return [];
  }
}

async function persistExpenses(records: ExpenseRecord[]): Promise<void> {
  const normalized = records.map(normalizeExpense);
  const sorted = sortByTimestampDescending(normalized);
  // recurringType이 undefined인 경우 null로 변환하여 저장 (JSON.stringify는 undefined를 제거함)
  const stringified = JSON.stringify(sorted, (key, value) => {
    if (key === 'recurringType' && value === undefined) {
      return null;
    }
    return value;
  });
  await AsyncStorage.setItem(EXPENSE_STORAGE_KEY, stringified);
}

/** 분석용: 할부(`isInstallment`) 우선, 다음 정기(`isRecurring`), 나머지 일반 */
export function expenseCreationVariantFromInstallmentFlags(
  isInstallment?: boolean,
  isRecurring?: boolean,
): ExpenseCreationVariant {
  if (isInstallment) {
    return 'repeated_isinstallment';
  }
  if (isRecurring) {
    return 'repeated_isrecurring';
  }
  return 'general';
}

export function expenseCreationVariantFromRecord(record: ExpenseRecord): ExpenseCreationVariant {
  return expenseCreationVariantFromInstallmentFlags(record.isInstallment, record.isRecurring);
}

/** Amplitude `record_created` / `record_deleted`용 소비 생애주기 속성 */
export function buildExpenseLifecycleAnalyticsPayload(
  record: ExpenseRecord,
): ExpenseLifecycleAnalyticsPayload {
  let repeat_kind: ExpenseRepeatKind = 'none';
  if (record.isInstallment) {
    repeat_kind = 'installment';
  } else if (record.isRecurring) {
    repeat_kind = 'recurring';
  }

  let period_months: number | null = null;
  if (record.isInstallment && typeof record.installmentMonths === 'number') {
    period_months = record.installmentMonths;
  } else if (record.isRecurring && typeof record.totalMonths === 'number') {
    period_months = record.totalMonths;
  }

  const wo = record.weekendOption;
  const weekend_option: ExpenseWeekendOptionAnalytics =
    wo === 'friday' || wo === 'monday' || wo === 'weekend' ? wo : 'none';

  let settlement_kind: ExpenseSettlementKind = 'none';
  if (record.isRefunded) {
    settlement_kind = 'refund';
  } else if (record.isSettled) {
    settlement_kind = 'settlement';
  } else if (record.isPrepaid) {
    settlement_kind = 'prepayment';
  }

  const refund_scope: ExpenseRefundScopeAnalytics | null = null;

  // `adjustment`는 `expense_adjustment` 이벤트와 동일한 네이밍 규약을 따른다.
  // 환불 > 결산 > 선결제 우선순위로 하나만 표기. 어느 것도 적용 안 된 기록은 null.
  let adjustment: ExpenseAdjustmentKind | null = null;
  if (record.isRefunded) adjustment = 'isrefunded';
  else if (record.isSettled) adjustment = 'issettled';
  else if (record.isPrepaid) adjustment = 'isprepaid';

  const state: ExpenseAdjustmentState | null = adjustment !== null ? 'applied' : null;

  return {
    repeat_kind,
    period_months,
    weekend_option,
    settlement_kind,
    refund_scope,
    adjustment,
    state,
  };
}

/**
 * 소비 화면 반복 옵션 라벨 → 분석용 `period_unit`.
 * 반복 토글 ON 시 UI가 항상 `recurringType`을 설정하므로, 여기서는 매핑만 수행한다.
 */
function mapRecurringTypeToPeriodUnit(recurringType: string): ExpensePeriodUnit {
  const label = recurringType.trim();
  switch (label) {
    case '매일':
      return 'daily';
    case '매주':
      return 'weekly';
    case '매월':
      return 'monthly';
    case '2주':
      return '2weeks';
    case '3주':
      return '3weeks';
    case '4주':
      return '4weeks';
    case '2개월 마다':
      return '2months';
    case '4개월 마다':
      return '4months';
    case '6개월 마다':
      return '6months';
    case '주중':
      return 'weekdays';
    case '주말':
      return 'weekends';
    default:
      throw new Error(`[analytics] 알 수 없는 정기 recurringType: ${JSON.stringify(label)}`);
  }
}

export type BuildExpenseCreationCompletionOpts = {
  /**
   * 같은 저장 배치(정기/할부 일괄 생성)에서 모든 `record_created`에 동일하게 실을 총 건수.
   * 미지정 시 정기는 `record.date` 기준 연말까지 횟수(건당 달라질 수 있음)로 계산.
   */
  repeatCountOverride?: number;
  /** 간편입력 경로 여부. 기본은 false (생성 화면 경로) */
  simpleCreation?: boolean;
};

function resolveSimpleCreation(
  record: ExpenseRecord,
  opts?: BuildExpenseCreationCompletionOpts,
): ExpenseSimpleCreationValue {
  // 생성 이벤트: 호출자가 명시적으로 넘긴 boolean이 우선
  if (typeof opts?.simpleCreation === 'boolean') {
    return opts.simpleCreation;
  }
  // 삭제 이벤트 등: 레코드의 출처 필드로 판단
  if (record.createdVia === 'simple') return true;
  if (record.createdVia === 'screen') return false;
  // 출처 추적이 없는 레거시 레코드
  return 'unknown';
}

export function buildExpenseCreationCompletionPayload(
  record: ExpenseRecord,
  opts?: BuildExpenseCreationCompletionOpts,
): ExpenseCreationCompletionPayload {
  const simpleCreation = resolveSimpleCreation(record, opts);
  const memo = typeof record.memo === 'string' && record.memo.trim().length > 0;

  if (record.isInstallment) {
    const months =
      typeof opts?.repeatCountOverride === 'number' && opts.repeatCountOverride >= 1
        ? opts.repeatCountOverride
        : typeof record.installmentMonths === 'number'
          ? Math.max(1, record.installmentMonths)
          : 1;
    return {
      repeat_count: months,
      simple_creation: simpleCreation,
      memo,
    };
  }

  if (record.isRecurring) {
    if (typeof record.recurringType !== 'string' || record.recurringType.trim() === '') {
      throw new Error('[analytics] 정기 기록인데 recurringType 이 비어 있음');
    }
    const label = record.recurringType.trim();
    const repeatCount =
      typeof opts?.repeatCountOverride === 'number' && opts.repeatCountOverride >= 1
        ? opts.repeatCountOverride
        : Math.max(1, calculateRecurringIterations(record.date, label));
    return {
      repeat_count: repeatCount,
      period_unit: mapRecurringTypeToPeriodUnit(label),
      simple_creation: simpleCreation,
      memo,
    };
  }

  return {
    repeat_count: 1,
    period_unit: 'none',
    simple_creation: simpleCreation,
    memo,
  };
}

export type CreateExpenseOptions = {
  /** expense-record 등에서 한 번에 집계할 때 개별 호출 로그 생략 */
  skipLifecycleLog?: boolean;
  /** 간편입력 경로 여부. 기본은 false (생성 화면 경로) */
  simpleCreation?: boolean;
};

export async function createExpense(
  record: ExpenseRecord,
  options?: CreateExpenseOptions,
): Promise<ExpenseRecord> {
  const expense = normalizeExpense(record);
  
  const existing = await loadLocalExpenses();
  const filtered = existing.filter(
    (item) =>
      !(item.id && expense.id && item.id === expense.id) && item.timestamp !== expense.timestamp,
  );
  filtered.push(expense);
  await persistExpenses(filtered);
  if (!options?.skipLifecycleLog) {
    logExpenseCreate(
      expenseCreationVariantFromRecord(expense),
      buildExpenseLifecycleAnalyticsPayload(expense),
      buildExpenseCreationCompletionPayload(expense, {
        simpleCreation: options?.simpleCreation === true,
      }),
    );
  }
  await registerReviewPromptLifetimeCreations(1);
  scheduleMaybePromptWriteReview();
  return expense;
}

export type CreateExpensesBatchOptions = {
  creationCompletionRepeatCount?: number;
  /** 간편입력 경로 여부. 기본은 false (생성 화면 경로) */
  simpleCreation?: boolean;
};

export async function createExpensesBatch(
  records: ExpenseRecord[],
  batchOptions?: CreateExpensesBatchOptions,
): Promise<ExpenseRecord[]> {
  if (records.length === 0) {
    return [];
  }

  const normalizedIncoming = records.map(normalizeExpense);
  const incomingIds = new Set<string>();
  const incomingTimestamps = new Set<number>();
  const dedupedIncoming: ExpenseRecord[] = [];

  for (const record of normalizedIncoming) {
    const id = record.id ?? '';
    const hasDuplicateId = id.length > 0 && incomingIds.has(id);
    const hasDuplicateTimestamp = incomingTimestamps.has(record.timestamp);
    if (hasDuplicateId || hasDuplicateTimestamp) {
      continue;
    }

    if (id.length > 0) {
      incomingIds.add(id);
    }
    incomingTimestamps.add(record.timestamp);
    dedupedIncoming.push(record);
  }

  if (dedupedIncoming.length === 0) {
    return [];
  }

  const existing = await loadLocalExpenses();
  const filteredExisting = existing.filter((item) => {
    if (item.id && incomingIds.has(item.id)) {
      return false;
    }
    return !incomingTimestamps.has(item.timestamp);
  });

  await persistExpenses([...filteredExisting, ...dedupedIncoming]);

  const batchRepeatCount =
    typeof batchOptions?.creationCompletionRepeatCount === 'number' &&
    batchOptions.creationCompletionRepeatCount >= 1
      ? batchOptions.creationCompletionRepeatCount
      : dedupedIncoming.length;

  if (dedupedIncoming.length > 0) {
    const anchor = dedupedIncoming[0];
    logExpenseCreate(
      expenseCreationVariantFromRecord(anchor),
      buildExpenseLifecycleAnalyticsPayload(anchor),
      buildExpenseCreationCompletionPayload(anchor, {
        repeatCountOverride: batchRepeatCount,
        simpleCreation: batchOptions?.simpleCreation === true,
      }),
    );
  }

  await registerReviewPromptLifetimeCreations(dedupedIncoming.length);
  scheduleMaybePromptWriteReview();
  return dedupedIncoming;
}

export async function updateExpense(
  id: string,
  updates: Partial<ExpenseRecord>,
): Promise<ExpenseRecord | null> {
  const expenses = await loadLocalExpenses();
  let updated: ExpenseRecord | null = null;

  const { createdAt: _discardCreatedAt, ...restUpdates } = updates;

  const next = expenses.map((expense) => {
    if (expense.id === id || expense.timestamp.toString() === id) {
      updated = normalizeExpense({
        ...expense,
        ...restUpdates,
        id: expense.id ?? id,
        createdAt: expense.createdAt,
        updatedAt: formatLocalDateTime(Date.now()),
      });
      return updated;
    }
    return expense;
  });

  if (!updated) {
    return null;
  }

  await persistExpenses(next);
  return updated;
}

export async function deleteExpense(id: string): Promise<boolean> {
  const expenses = await loadLocalExpenses();
  const target = expenses.find(
    (expense) => expense.id === id || expense.timestamp.toString() === id,
  );
  if (!target) {
    return false;
  }

  const filtered = expenses.filter(
    (expense) => expense.id !== id && expense.timestamp.toString() !== id,
  );

  await persistExpenses(filtered);
  logExpenseDelete(
    expenseCreationVariantFromRecord(target),
    buildExpenseLifecycleAnalyticsPayload(target),
    buildExpenseCreationCompletionPayload(target),
  );
  return true;
}

export async function getExpenseById(id: string): Promise<ExpenseRecord | null> {
  const expenses = await loadLocalExpenses();
  return (
    expenses.find(
      (expense) => expense.id === id || expense.timestamp.toString() === id,
    ) ?? null
  );
}

export async function getExpensesByDateRange(
  startDate: string,
  endDate: string,
): Promise<ExpenseRecord[]> {
  const expenses = await loadLocalExpenses();
  return expenses
    .filter(
      (expense) =>
        !expense.isDeleted && isWithinDateRange(expense.date, startDate, endDate),
    )
    .sort((a, b) => b.timestamp - a.timestamp);
}

export async function getExpensesByRecurringId(recurringId: string): Promise<ExpenseRecord[]> {
  if (!recurringId) {
    return [];
  }

  const expenses = await loadLocalExpenses();
  return sortByTimestampAscending(
    expenses.filter((expense) => expense.recurringId === recurringId && !expense.isDeleted),
  );
}

export async function getExpensesByInstallmentId(installmentId: string): Promise<ExpenseRecord[]> {
  if (!installmentId) {
    return [];
  }

  const expenses = await loadLocalExpenses();
  return sortByTimestampAscending(
    expenses.filter((expense) => expense.installmentId === installmentId && !expense.isDeleted),
  );
}

export async function getAllExpenses(): Promise<ExpenseRecord[]> {
  return loadLocalExpenses();
}

/**
 * 모든 지출 기록에서 카테고리명을 변경합니다.
 */
export async function renameExpenseCategory(
  oldLabel: string,
  newLabel: string
): Promise<void> {
  const expenses = await loadLocalExpenses();
  let changed = false;
  const nowLocal = formatLocalDateTime(Date.now());
  const updated = expenses.map((expense) => {
    if (expense.category === oldLabel) {
      changed = true;
      return normalizeExpense({
        ...expense,
        category: newLabel,
        updatedAt: nowLocal,
      });
    }
    return expense;
  });
  if (changed) {
    await persistExpenses(updated);
  }
}

/**
 * 특정 카테고리에 해당하는 지출 기록을 모두 삭제합니다.
 */
export async function deleteExpensesByCategory(categoryLabel: string): Promise<void> {
  const expenses = await loadLocalExpenses();
  const removedRecords = expenses.filter((expense) => expense.category === categoryLabel);
  if (removedRecords.length === 0) {
    return;
  }
  const filtered = expenses.filter((expense) => expense.category !== categoryLabel);
  await persistExpenses(filtered);
  for (const r of removedRecords) {
    logExpenseDelete(
      expenseCreationVariantFromRecord(r),
      buildExpenseLifecycleAnalyticsPayload(r),
      buildExpenseCreationCompletionPayload(r),
    );
  }
}

export async function clearAllExpenses(): Promise<void> {
  await AsyncStorage.removeItem(EXPENSE_STORAGE_KEY);
}

/**
 * 복원용: 전체 지출 데이터를 주어진 배열로 교체합니다.
 */
export async function replaceAllExpenses(records: ExpenseRecord[]): Promise<void> {
  await persistExpenses(records);
}

export async function deleteExpensesByGroup(params: {
  recurringId?: string | null;
  installmentId?: string | null;
}): Promise<void> {
  const { recurringId = null, installmentId = null } = params;
  if (!recurringId && !installmentId) {
    return;
  }

  const expenses = await loadLocalExpenses();
  const toRemove = expenses.filter((expense) => {
    if (recurringId && expense.recurringId === recurringId) {
      return true;
    }
    if (installmentId && expense.installmentId === installmentId) {
      return true;
    }
    return false;
  });

  const filtered = expenses.filter((expense) => !toRemove.includes(expense));

  if (toRemove.length === 0) {
    return;
  }

  await persistExpenses(filtered);
  // 정기/할부 그룹 삭제: 생성과 동일하게 이벤트 1회만 (repeat_count = 실제 삭제 건수)
  const anchor = toRemove[0];
  logExpenseDelete(
    expenseCreationVariantFromRecord(anchor),
    buildExpenseLifecycleAnalyticsPayload(anchor),
    buildExpenseCreationCompletionPayload(anchor, {
      repeatCountOverride: toRemove.length,
    }),
  );
}

