import AsyncStorage from '@react-native-async-storage/async-storage';
import { generateRecordId } from './id-generator';

export type PaymentMethod = 'credit' | 'debit' | 'cash';

export interface ExpenseRecord {
  id?: string; // UUID v4 (생성 시 자동 할당)
  type: 'expense';
  amount: number;
  category: string;
  memo?: string;
  date: string; // YYYY.MM.DD 형식
  timestamp: number;
  paymentMethod?: PaymentMethod;
  isRecurring?: boolean;
  weekendOption?: 'friday' | 'monday' | 'weekend';
  recurringId?: string;
  installmentId?: string;
  isAutoGenerated?: boolean;
  isInstallment?: boolean;
  totalMonths?: number; // 정기 기록 개월 수
  installmentMonths?: number; // 할부 기록 개월 수
  originalInstallment?: boolean;
  recurringType?: string; // 정기 기록의 반복 타입 (매일, 매주, 2주, 3주, 4주, 매월, 2개월 마다, 4개월 마다, 6개월 마다, 주중, 주말)
  isPrepaid?: boolean;
  prepaidDate?: string; // YYYY.MM.DD 형식
  isRefunded?: boolean;
  isSettled?: boolean;
  settledAt?: string;
  originalAmountBeforeSettlement?: number;
  installmentOriginDate?: string; // 할부 기록 원본 예정일 (선결제 시 사용)
  isDeleted?: boolean;
  deletedAt?: string | null;
  originalAmount?: number; // 원본 금액
  originalAmountBeforeRefund?: number; // 환불 직전 금액
  originalCategory?: string; // 원본 카테고리
  originalDate?: string; // 원본 날짜 (YYYY.MM.DD 형식) - 일반 기록: 처음 생성일, 선결제 기록: 원래 예정일
}

const EXPENSE_STORAGE_KEY = 'expenseData';
const DATE_TOKEN_REGEX = /\./g;

function normalizeExpense(record: ExpenseRecord): ExpenseRecord {
  const normalized = {
    ...record,
    id: record.id ?? generateRecordId(),
    type: 'expense',
    isDeleted: record.isDeleted ?? false,
    deletedAt: record.deletedAt ?? null,
    paymentMethod: record.paymentMethod ?? 'credit',
  };
  
  return normalized;
}

function sortByTimestampDescending(records: ExpenseRecord[]): ExpenseRecord[] {
  return [...records].sort((a, b) => b.timestamp - a.timestamp);
}

function sortByTimestampAscending(records: ExpenseRecord[]): ExpenseRecord[] {
  return [...records].sort((a, b) => a.timestamp - b.timestamp);
}

function isWithinDateRange(date: string, startDate: string, endDate: string): boolean {
  const normalizedDate = date.replace(DATE_TOKEN_REGEX, '');
  const normalizedStart = startDate.replace(DATE_TOKEN_REGEX, '');
  const normalizedEnd = endDate.replace(DATE_TOKEN_REGEX, '');
  return normalizedDate >= normalizedStart && normalizedDate <= normalizedEnd;
}

async function loadLocalExpenses(): Promise<ExpenseRecord[]> {
  try {
    const stored = await AsyncStorage.getItem(EXPENSE_STORAGE_KEY);
    if (!stored) {
      return [];
    }

    // recurringType이 null인 경우 undefined로 변환 (JSON.parse reviver)
    const parsed = JSON.parse(stored, (key, value) => {
      if (key === 'recurringType' && value === null) {
        return undefined;
      }
      return value;
    });
    if (!Array.isArray(parsed)) {
      return [];
    }

    return sortByTimestampDescending(
      parsed.map((item) =>
        normalizeExpense({
          ...item,
          timestamp: typeof item.timestamp === 'number' ? item.timestamp : Number(item.timestamp),
        }),
      ),
    );
  } catch (error) {
    console.error('[expenses] Failed to load local expenses:', error);
    return [];
  }
}

async function persistExpenses(records: ExpenseRecord[]): Promise<void> {
  const normalized = records.map(normalizeExpense);
  const sorted = sortByTimestampDescending(normalized);
  // recurringType이 undefined인 경우 null로 변환하여 저장 (JSON.stringify는 undefined를 제거함)
  const stringified = JSON.stringify(sorted, (key, value) => {
    if (key === 'recurringType' && value === undefined) {
      return null;
    }
    return value;
  });
  await AsyncStorage.setItem(EXPENSE_STORAGE_KEY, stringified);
}

export async function createExpense(record: ExpenseRecord): Promise<ExpenseRecord> {
  const expense = normalizeExpense(record);
  
  const existing = await loadLocalExpenses();
  const filtered = existing.filter(
    (item) =>
      !(item.id && expense.id && item.id === expense.id) && item.timestamp !== expense.timestamp,
  );
  filtered.push(expense);
  await persistExpenses(filtered);
  
  return expense;
}

export async function createExpensesBatch(records: ExpenseRecord[]): Promise<ExpenseRecord[]> {
  if (records.length === 0) {
    return [];
  }

  const normalizedIncoming = records.map(normalizeExpense);
  const incomingIds = new Set<string>();
  const incomingTimestamps = new Set<number>();
  const dedupedIncoming: ExpenseRecord[] = [];

  for (const record of normalizedIncoming) {
    const id = record.id ?? '';
    const hasDuplicateId = id.length > 0 && incomingIds.has(id);
    const hasDuplicateTimestamp = incomingTimestamps.has(record.timestamp);
    if (hasDuplicateId || hasDuplicateTimestamp) {
      continue;
    }

    if (id.length > 0) {
      incomingIds.add(id);
    }
    incomingTimestamps.add(record.timestamp);
    dedupedIncoming.push(record);
  }

  if (dedupedIncoming.length === 0) {
    return [];
  }

  const existing = await loadLocalExpenses();
  const filteredExisting = existing.filter((item) => {
    if (item.id && incomingIds.has(item.id)) {
      return false;
    }
    return !incomingTimestamps.has(item.timestamp);
  });

  await persistExpenses([...filteredExisting, ...dedupedIncoming]);
  return dedupedIncoming;
}

export async function updateExpense(
  id: string,
  updates: Partial<ExpenseRecord>,
): Promise<ExpenseRecord | null> {
  const expenses = await loadLocalExpenses();
  let updated: ExpenseRecord | null = null;

  const next = expenses.map((expense) => {
    if (expense.id === id || expense.timestamp.toString() === id) {
      updated = normalizeExpense({
        ...expense,
        ...updates,
        id: expense.id ?? id,
      });
      return updated;
    }
    return expense;
  });

  if (!updated) {
    return null;
  }

  await persistExpenses(next);
  return updated;
}

export async function deleteExpense(id: string): Promise<boolean> {
  const expenses = await loadLocalExpenses();
  const filtered = expenses.filter(
    (expense) => expense.id !== id && expense.timestamp.toString() !== id,
  );
  if (filtered.length === expenses.length) {
    return false;
  }

  await persistExpenses(filtered);
  return true;
}

export async function getExpenseById(id: string): Promise<ExpenseRecord | null> {
  const expenses = await loadLocalExpenses();
  return (
    expenses.find(
      (expense) => expense.id === id || expense.timestamp.toString() === id,
    ) ?? null
  );
}

export async function getExpensesByDateRange(
  startDate: string,
  endDate: string,
): Promise<ExpenseRecord[]> {
  const expenses = await loadLocalExpenses();
  return expenses
    .filter(
      (expense) =>
        !expense.isDeleted && isWithinDateRange(expense.date, startDate, endDate),
    )
    .sort((a, b) => b.timestamp - a.timestamp);
}

export async function getExpensesByRecurringId(recurringId: string): Promise<ExpenseRecord[]> {
  if (!recurringId) {
    return [];
  }

  const expenses = await loadLocalExpenses();
  return sortByTimestampAscending(
    expenses.filter((expense) => expense.recurringId === recurringId && !expense.isDeleted),
  );
}

export async function getExpensesByInstallmentId(installmentId: string): Promise<ExpenseRecord[]> {
  if (!installmentId) {
    return [];
  }

  const expenses = await loadLocalExpenses();
  return sortByTimestampAscending(
    expenses.filter((expense) => expense.installmentId === installmentId && !expense.isDeleted),
  );
}

export async function getAllExpenses(): Promise<ExpenseRecord[]> {
  return loadLocalExpenses();
}

/**
 * 모든 지출 기록에서 카테고리명을 변경합니다.
 */
export async function renameExpenseCategory(
  oldLabel: string,
  newLabel: string
): Promise<void> {
  const expenses = await loadLocalExpenses();
  let changed = false;
  const updated = expenses.map((expense) => {
    if (expense.category === oldLabel) {
      changed = true;
      return { ...expense, category: newLabel };
    }
    return expense;
  });
  if (changed) {
    await persistExpenses(updated);
  }
}

/**
 * 특정 카테고리에 해당하는 지출 기록을 모두 삭제합니다.
 */
export async function deleteExpensesByCategory(categoryLabel: string): Promise<void> {
  const expenses = await loadLocalExpenses();
  const filtered = expenses.filter((expense) => expense.category !== categoryLabel);
  if (filtered.length !== expenses.length) {
    await persistExpenses(filtered);
  }
}

export async function clearAllExpenses(): Promise<void> {
  await AsyncStorage.removeItem(EXPENSE_STORAGE_KEY);
}

export async function deleteExpensesByGroup(params: {
  recurringId?: string | null;
  installmentId?: string | null;
}): Promise<void> {
  const { recurringId = null, installmentId = null } = params;
  if (!recurringId && !installmentId) {
    return;
  }

  const expenses = await loadLocalExpenses();
  const filtered = expenses.filter((expense) => {
    if (recurringId && expense.recurringId === recurringId) {
      return false;
    }
    if (installmentId && expense.installmentId === installmentId) {
      return false;
    }
    return true;
  });

  await persistExpenses(filtered);
}

