import { loadAllCategories } from '@/utils/categories';
import { calculateRecurringIterations } from '@/utils/expense-calculations';
import {
  deleteExpensesByGroup,
  getAllExpenses,
  type ExpenseRecord,
} from '@/utils/expenses';
import { extractTimestampFromId } from '@/utils/id-generator';

export type RecurringGroupKind = 'recurring' | 'installment';

export interface RecurringInstallmentGroupSummary {
  kind: RecurringGroupKind;
  groupId: string;
  /** 카테고리명 (이모지 제외) */
  category: string;
  /** 화면 표시용: 이모지 + 카테고리명 */
  categoryDisplay: string;
  /** 화면 표시용 메모 */
  memo: string;
  amount: number;
  repeatSettingLabel: string;
  startDate: string;
  endDate: string;
}

const DAILY_RECURRING_TYPES = new Set(['매일', '매주', '2주', '3주', '4주', '주중', '주말']);

function parseExpenseDate(date: string): Date | null {
  const parts = date.split('.').map((part) => parseInt(part.trim(), 10));
  if (parts.length < 3 || parts.some((value) => Number.isNaN(value))) {
    return null;
  }
  return new Date(parts[0], parts[1] - 1, parts[2]);
}

function formatDotDate(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}. ${month}. ${day}`;
}

function getWeekendLabel(
  weekendOption: ExpenseRecord['weekendOption'],
  recurringType?: string,
  isRecurring?: boolean,
): string {
  const shouldIgnoreWeekendOption =
    isRecurring === true &&
    typeof recurringType === 'string' &&
    DAILY_RECURRING_TYPES.has(recurringType);

  if (shouldIgnoreWeekendOption) {
    return '주말 관계없이 기록';
  }

  if (weekendOption === 'friday') {
    return '금주 금요일 기록';
  }
  if (weekendOption === 'monday') {
    return '차주 월요일 기록';
  }
  return '관계없이 주말 기록';
}

function buildRepeatSettingLabel(anchor: ExpenseRecord, monthCount: number): string {
  const weekendText = getWeekendLabel(anchor.weekendOption, anchor.recurringType, anchor.isRecurring);

  if (anchor.isInstallment) {
    return `할부 ⋅ ${monthCount}개월 ⋅ ${weekendText}`;
  }

  const recurringType = anchor.recurringType?.trim() || '매월';
  return `정기지출 ⋅ ${recurringType} ⋅ ${weekendText}`;
}

/**
 * 반복/할부 그룹의 최초 생성 기록.
 * 이후 개별 회차 메모 수정과 무관하게 생성 시점(첫 회차) 데이터를 기준으로 합니다.
 */
function resolveCreationRecord(records: ExpenseRecord[], groupId: string): ExpenseRecord {
  const sortedAll = records.slice().sort((a, b) => a.timestamp - b.timestamp);
  if (sortedAll.length === 0) {
    throw new Error('[recurring-record-management] empty group records');
  }

  const groupTimestamp = extractTimestampFromId(groupId);
  if (groupTimestamp != null) {
    const matchedByGroupId = sortedAll.find(
      (record) => record.timestamp === groupTimestamp || record.id === groupId,
    );
    if (matchedByGroupId) {
      return matchedByGroupId;
    }
  }

  const nonAutoGenerated = sortedAll.filter((record) => record.isAutoGenerated !== true);
  if (nonAutoGenerated.length > 0) {
    return nonAutoGenerated[0];
  }

  return sortedAll[0];
}

function resolveAnchorRecord(records: ExpenseRecord[], groupId: string): ExpenseRecord {
  return resolveCreationRecord(records, groupId);
}

function resolveMonthCount(anchor: ExpenseRecord, records: ExpenseRecord[]): number {
  if (anchor.isInstallment) {
    if (typeof anchor.installmentMonths === 'number' && anchor.installmentMonths > 0) {
      return anchor.installmentMonths;
    }
    return records.length;
  }

  if (typeof anchor.totalMonths === 'number' && anchor.totalMonths > 0) {
    return anchor.totalMonths;
  }

  if (anchor.recurringType) {
    return Math.max(1, calculateRecurringIterations(anchor.date, anchor.recurringType));
  }

  return records.length;
}

function resolveStartDate(anchor: ExpenseRecord, groupId: string): Date {
  const fromOriginal = anchor.originalDate ? parseExpenseDate(anchor.originalDate) : null;
  if (fromOriginal) {
    return fromOriginal;
  }

  const fromDate = parseExpenseDate(anchor.date);
  if (fromDate) {
    return fromDate;
  }

  // Legacy fallback: 일부 과거 데이터는 groupId에서 시작 시점을 복원합니다.
  const fromId = extractTimestampFromId(groupId);
  if (fromId) {
    return new Date(fromId);
  }

  return new Date(anchor.timestamp);
}

function resolveEndDate(
  anchor: ExpenseRecord,
  records: ExpenseRecord[],
  startDate: Date,
  monthCount: number,
): Date {
  let latest = startDate;

  records.forEach((record) => {
    const parsed = parseExpenseDate(record.date);
    if (parsed && parsed > latest) {
      latest = parsed;
    }
  });

  if (anchor.isRecurring && anchor.recurringType && DAILY_RECURRING_TYPES.has(anchor.recurringType)) {
    const yearEnd = new Date(startDate.getFullYear(), 11, 31);
    return latest > yearEnd ? latest : yearEnd;
  }

  const calculated = new Date(
    startDate.getFullYear(),
    startDate.getMonth() + Math.max(0, monthCount - 1),
    startDate.getDate(),
  );

  return latest > calculated ? latest : calculated;
}

function resolveGroupKey(expense: ExpenseRecord): string | null {
  if (expense.isDeleted) {
    return null;
  }

  const installmentId =
    expense.isInstallment === true ? expense.installmentId?.trim() : undefined;
  if (installmentId && installmentId.length > 0) {
    return `installment:${installmentId}`;
  }

  const recurringId =
    expense.isRecurring === true ? expense.recurringId?.trim() : undefined;
  if (recurringId && recurringId.length > 0) {
    return `recurring:${recurringId}`;
  }

  return null;
}

function groupRecords(expenses: ExpenseRecord[]): Map<string, ExpenseRecord[]> {
  const groups = new Map<string, ExpenseRecord[]>();

  expenses.forEach((expense) => {
    const key = resolveGroupKey(expense);
    if (!key) {
      return;
    }

    const existing = groups.get(key);
    if (existing) {
      existing.push(expense);
    } else {
      groups.set(key, [expense]);
    }
  });

  return groups;
}

function formatCategoryDisplay(label: string, emojiByLabel: Map<string, string>): string {
  const emoji = emojiByLabel.get(label);
  return emoji ? `${emoji} ${label}` : label;
}

function summarizeGroup(
  key: string,
  records: ExpenseRecord[],
  emojiByLabel: Map<string, string>,
): RecurringInstallmentGroupSummary {
  const kind: RecurringGroupKind = key.startsWith('recurring:') ? 'recurring' : 'installment';
  const groupId = key.split(':')[1] ?? '';
  const anchor = resolveAnchorRecord(records, groupId);
  const monthCount = resolveMonthCount(anchor, records);
  const startDate = resolveStartDate(anchor, groupId);
  const endDate = resolveEndDate(anchor, records, startDate, monthCount);
  const category = anchor.category;

  return {
    kind,
    groupId,
    category,
    categoryDisplay: formatCategoryDisplay(category, emojiByLabel),
    memo: anchor.memo?.trim() ?? '',
    amount: anchor.originalAmount ?? anchor.amount,
    repeatSettingLabel: buildRepeatSettingLabel(anchor, monthCount),
    startDate: formatDotDate(startDate),
    endDate: formatDotDate(endDate),
  };
}

function groupOverlapsYear(records: ExpenseRecord[], year: number): boolean {
  return records.some((record) => {
    const parsed = parseExpenseDate(record.date);
    return parsed?.getFullYear() === year;
  });
}

export async function hasAnyRecurringInstallmentGroups(): Promise<boolean> {
  const expenses = await getAllExpenses();
  return groupRecords(expenses).size > 0;
}

export async function listRecurringInstallmentGroups(
  year: number,
): Promise<RecurringInstallmentGroupSummary[]> {
  const [expenses, categories] = await Promise.all([getAllExpenses(), loadAllCategories()]);
  const emojiByLabel = new Map(categories.map((category) => [category.label, category.emoji]));
  const summaries: RecurringInstallmentGroupSummary[] = [];

  groupRecords(expenses).forEach((records, key) => {
    if (!groupOverlapsYear(records, year)) {
      return;
    }
    summaries.push(summarizeGroup(key, records, emojiByLabel));
  });

  return summaries.sort((a, b) => {
    const aTime = parseExpenseDate(a.startDate)?.getTime() ?? 0;
    const bTime = parseExpenseDate(b.startDate)?.getTime() ?? 0;
    return bTime - aTime;
  });
}

export async function deleteRecurringInstallmentGroup(
  summary: Pick<RecurringInstallmentGroupSummary, 'kind' | 'groupId'>,
): Promise<void> {
  if (summary.kind === 'recurring') {
    await deleteExpensesByGroup({ recurringId: summary.groupId });
    return;
  }

  await deleteExpensesByGroup({ installmentId: summary.groupId });
}
