import type { DayDataRecord } from '@/contexts/app-data-context';
import { isDateInCustomMonth } from '@/utils/custom-month';

export interface TimelineListItem {
  id?: string;
  date: string;
  type: 'income' | 'expense';
  category: string;
  memo?: string;
  amount: number;
  timestamp?: number;
  isRecurring?: boolean;
  weekendOption?: 'weekend' | 'friday' | 'monday';
  recurringType?: string;
  paymentMethod?: 'credit' | 'debit' | 'cash';
  paymentSubtypeId?: string;
  isPrepaid?: boolean;
  prepaidDate?: string;
  recurringId?: string;
  installmentId?: string;
  installmentOriginDate?: string;
  originalDate?: string;
  isAutoGenerated?: boolean;
  actualRecordIndex?: number;
  isInstallment?: boolean;
  originalInstallment?: boolean;
  totalMonths?: number;
  isRefunded?: boolean;
  isSettled?: boolean;
  settledAt?: string;
  originalAmountBeforeSettlement?: number;
}

/**
 * AppDataContext calendarData → 타임라인 리스트 (AsyncStorage 재파싱 없음).
 */
export function buildTimelineItemsFromCalendarData(
  calendarData: DayDataRecord,
  year: number,
  month: number,
  monthStartDay: number,
): TimelineListItem[] {
  const items: TimelineListItem[] = [];

  Object.entries(calendarData).forEach(([dateString, data]: [string, DayDataRecord[string]]) => {
    const [yearStr, monthStr, dayStr] = dateString.split('-');
    const date = new Date(parseInt(yearStr, 10), parseInt(monthStr, 10) - 1, parseInt(dayStr, 10));

    if (!isDateInCustomMonth(date, year, month, monthStartDay)) {
      return;
    }

    if (!data?.records || !Array.isArray(data.records)) {
      return;
    }

    data.records.forEach((record: Record<string, unknown>, recordIndex: number) => {
      if (record?.isDeleted === true) {
        return;
      }

      items.push({
        id: typeof record.id === 'string' ? record.id : undefined,
        date: dateString,
        type: record.type === 'income' ? 'income' : 'expense',
        category: typeof record.category === 'string' ? record.category : '기타',
        memo: typeof record.memo === 'string' ? record.memo : undefined,
        amount: typeof record.amount === 'number' ? record.amount : 0,
        timestamp: typeof record.timestamp === 'number' ? record.timestamp : undefined,
        paymentMethod:
          record.type === 'expense'
            ? (record.paymentMethod as TimelineListItem['paymentMethod']) ?? 'credit'
            : undefined,
        paymentSubtypeId:
          record.type === 'expense' && typeof record.paymentSubtypeId === 'string'
            ? record.paymentSubtypeId
            : undefined,
        isRecurring: record.isRecurring === true,
        weekendOption: record.weekendOption as TimelineListItem['weekendOption'],
        recurringType:
          record.recurringType === null || record.recurringType === undefined
            ? undefined
            : String(record.recurringType),
        isPrepaid: record.isPrepaid === true,
        prepaidDate: typeof record.prepaidDate === 'string' ? record.prepaidDate : undefined,
        recurringId: typeof record.recurringId === 'string' ? record.recurringId : undefined,
        installmentId: typeof record.installmentId === 'string' ? record.installmentId : undefined,
        installmentOriginDate:
          typeof record.installmentOriginDate === 'string' ? record.installmentOriginDate : undefined,
        originalDate: typeof record.originalDate === 'string' ? record.originalDate : undefined,
        isAutoGenerated: record.isAutoGenerated === true,
        actualRecordIndex: recordIndex,
        isInstallment: record.isInstallment === true,
        originalInstallment: record.originalInstallment === true,
        totalMonths: typeof record.totalMonths === 'number' ? record.totalMonths : undefined,
        isRefunded: record.isRefunded === true,
        isSettled: record.isSettled === true,
        settledAt: typeof record.settledAt === 'string' ? record.settledAt : undefined,
        originalAmountBeforeSettlement:
          typeof record.originalAmountBeforeSettlement === 'number'
            ? record.originalAmountBeforeSettlement
            : undefined,
      });
    });
  });

  items.sort((a, b) => {
    const dateCompare = new Date(b.date).getTime() - new Date(a.date).getTime();
    if (dateCompare !== 0) {
      return dateCompare;
    }
    return (b.timestamp || 0) - (a.timestamp || 0);
  });

  return items;
}
